using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Map;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace StoryMode;

public class CampaignStoryMode : Campaign
{
	[SaveableProperty(9999)]
	public StoryModeManager StoryMode { get; private set; }

	public CampaignStoryMode(CampaignGameMode gameMode)
		: base(gameMode)
	{
		//IL_0001: Unknown result type (might be due to invalid IL or missing references)
		StoryMode = new StoryModeManager();
	}

	protected override void BeforeRegisterTypes(MBObjectManager objectManager)
	{
		((Campaign)this).BeforeRegisterTypes(objectManager);
		objectManager.RegisterType<TrainingField>("TrainingField", "TrainingFields", 1u, true, false);
	}

	protected override void DoLoadingForGameType(GameTypeLoadingStates gameTypeLoadingState, out GameTypeLoadingStates nextState)
	{
		//IL_0001: Unknown result type (might be due to invalid IL or missing references)
		//IL_0008: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_001d: Invalid comparison between Unknown and I4
		//IL_000d: Unknown result type (might be due to invalid IL or missing references)
		//IL_000e: Invalid comparison between I4 and Unknown
		//IL_004c: Unknown result type (might be due to invalid IL or missing references)
		//IL_004e: Invalid comparison between Unknown and I4
		//IL_0021: Unknown result type (might be due to invalid IL or missing references)
		//IL_0022: Invalid comparison between I4 and Unknown
		//IL_003f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0044: Unknown result type (might be due to invalid IL or missing references)
		((Campaign)this).DoLoadingForGameType(gameTypeLoadingState, ref nextState);
		if ((int)gameTypeLoadingState == 0 && (int)nextState != (int)gameTypeLoadingState)
		{
			StoryMode.InitializeStoryModeObjects();
		}
		if ((int)gameTypeLoadingState == 2 && (int)nextState != (int)gameTypeLoadingState)
		{
			Settlement val = Settlement.Find("tutorial_training_field");
			if (val != null)
			{
				IMapScene mapSceneWrapper = ((Campaign)this).MapSceneWrapper;
				string stringId = ((MBObjectBase)val).StringId;
				CampaignVec2 position = val.Position;
				mapSceneWrapper.AddNewEntityToMapScene(stringId, ref position);
			}
		}
		if ((int)gameTypeLoadingState == 3)
		{
			OnSessionLaunched();
		}
	}

	private void OnSessionLaunched()
	{
		StoryMode.MainStoryLine.OnSessionLaunched();
	}

	internal static void AutoGeneratedStaticCollectObjectsCampaignStoryMode(object o, List<object> collectedObjects)
	{
		((GameType)(CampaignStoryMode)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		((Campaign)this).AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(StoryMode);
	}

	internal static object AutoGeneratedGetMemberValueStoryMode(object o)
	{
		return ((CampaignStoryMode)o).StoryMode;
	}
}
