using System.Collections.Generic;
using System.Xml;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.ObjectSystem;

namespace StoryMode;

public class TrainingField : SettlementComponent
{
	public override IFaction MapFaction => null;

	internal static void AutoGeneratedStaticCollectObjectsTrainingField(object o, List<object> collectedObjects)
	{
		((MBObjectBase)(TrainingField)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		((SettlementComponent)this).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	public override void Deserialize(MBObjectManager objectManager, XmlNode node)
	{
		((SettlementComponent)this).Deserialize(objectManager, node);
		if (node.Attributes["background_crop_position"] != null)
		{
			((SettlementComponent)this).BackgroundCropPosition = float.Parse(node.Attributes["background_crop_position"].Value);
		}
		if (node.Attributes["background_mesh"] != null)
		{
			((SettlementComponent)this).BackgroundMeshName = node.Attributes["background_mesh"].Value;
		}
		if (node.Attributes["wait_mesh"] != null)
		{
			((SettlementComponent)this).WaitMeshName = node.Attributes["wait_mesh"].Value;
		}
	}
}
