using System;
using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;

namespace TaleWorlds.CampaignSystem.Incidents;

public class Incident : MBObjectBase
{
	public delegate bool IncidentOptionConditionDelegate(TextObject text);

	public delegate void IncidentOptionConsequenceDelegate();

	private readonly struct IncidentOption
	{
		public readonly TextObject Text;

		public readonly IncidentOptionConditionDelegate Condition;

		public readonly IncidentOptionConsequenceDelegate Consequence;

		private readonly List<IncidentEffect> _effects;

		public IReadOnlyList<IncidentEffect> Effects => _effects;

		public IncidentOption(TextObject text, List<IncidentEffect> effects, IncidentOptionConditionDelegate condition, IncidentOptionConsequenceDelegate consequence)
		{
			Text = text;
			_effects = effects;
			Condition = condition;
			Consequence = consequence;
		}
	}

	private Func<TextObject, bool> _condition;

	private List<IncidentOption> _options;

	public TextObject Title { get; private set; }

	public TextObject Description { get; private set; }

	public IncidentsCampaignBehaviour.IncidentTrigger Trigger { get; private set; }

	public IncidentsCampaignBehaviour.IncidentType Type { get; private set; }

	public CampaignTime Cooldown { get; private set; }

	public int NumOfOptions => _options.Count;

	internal static void AutoGeneratedStaticCollectObjectsIncident(object o, List<object> collectedObjects)
	{
		((Incident)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	public void Initialize(string title, string description, IncidentsCampaignBehaviour.IncidentTrigger trigger, IncidentsCampaignBehaviour.IncidentType type, CampaignTime cooldown, Func<TextObject, bool> condition)
	{
		Title = new TextObject(title);
		Description = new TextObject(description);
		Trigger = trigger;
		Type = type;
		Cooldown = cooldown;
		_condition = condition;
		_options = new List<IncidentOption>();
		base.IsReady = true;
	}

	public Incident(string id)
		: base(id)
	{
	}

	public void AddOption(string text, List<IncidentEffect> effects, IncidentOptionConditionDelegate condition = null, IncidentOptionConsequenceDelegate consequence = null)
	{
		IncidentOption item = new IncidentOption(new TextObject(text), effects, condition, consequence);
		_options.Add(item);
	}

	public bool CanIncidentBeInvoked()
	{
		if (_condition(Description))
		{
			foreach (IncidentOption option in _options)
			{
				if (option.Condition != null && !option.Condition(option.Text))
				{
					return false;
				}
				foreach (IncidentEffect effect in option.Effects)
				{
					if (!effect.Condition())
					{
						return false;
					}
				}
			}
			return true;
		}
		return false;
	}

	public TextObject GetOptionText(int index)
	{
		return _options[index].Text;
	}

	public List<TextObject> GetOptionHint(int index)
	{
		List<TextObject> list = _options[index].Effects.SelectMany((IncidentEffect x) => x.GetHint()).ToList();
		if (list.Count == 0)
		{
			list.Add(new TextObject("{=lobJVVWT}Nothing happens"));
		}
		return list;
	}

	public List<TextObject> InvokeOption(int index)
	{
		IncidentOption incidentOption = _options[index];
		List<TextObject> list = new List<TextObject>();
		foreach (IncidentEffect effect in incidentOption.Effects)
		{
			list.AddRange(effect.Consequence());
		}
		incidentOption.Consequence?.Invoke();
		CampaignEventDispatcher.Instance.OnIncidentResolved(this);
		return list;
	}
}
