using System.Collections.Generic;
using System.Linq;
using Helpers;
using TaleWorlds.CampaignSystem.CampaignBehaviors;
using TaleWorlds.CampaignSystem.CharacterDevelopment;
using TaleWorlds.CampaignSystem.Extensions;
using TaleWorlds.Core;
using TaleWorlds.Core.ImageIdentifiers;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Election;

public class StartAllianceDecision : KingdomDecision
{
	public class StartAllianceDecisionOutcome : DecisionOutcome
	{
		[SaveableField(100)]
		public readonly bool ShouldAllianceBeStarted;

		[SaveableField(110)]
		public readonly Kingdom Kingdom;

		[SaveableField(120)]
		public readonly Kingdom KingdomToStartAllianceWith;

		public StartAllianceDecisionOutcome(bool shouldAllianceBeStarted, Kingdom kingdom, Kingdom kingdomToStartAllianceWith)
		{
			ShouldAllianceBeStarted = shouldAllianceBeStarted;
			Kingdom = kingdom;
			KingdomToStartAllianceWith = kingdomToStartAllianceWith;
		}

		public override TextObject GetDecisionTitle()
		{
			TextObject textObject = new TextObject("{=kakxnaN5}{?SUPPORT}Yes{?}No{\\?}");
			textObject.SetTextVariable("SUPPORT", ShouldAllianceBeStarted ? 1 : 0);
			return textObject;
		}

		public override TextObject GetDecisionDescription()
		{
			if (ShouldAllianceBeStarted)
			{
				TextObject textObject = new TextObject("{=k3418kiP}It is time to form alliance with {KINGDOM_NAME}.");
				textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
				return textObject;
			}
			TextObject textObject2 = new TextObject("{=M1X2R8Uv}We oppose forming an alliance with {KINGDOM_NAME}.");
			textObject2.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
			return textObject2;
		}

		public override string GetDecisionLink()
		{
			return null;
		}

		public override ImageIdentifier GetDecisionImageIdentifier()
		{
			return null;
		}
	}

	[SaveableField(101)]
	public readonly Kingdom KingdomToStartAllianceWith;

	private IAllianceCampaignBehavior _allianceCampaignBehavior;

	public IAllianceCampaignBehavior AllianceCampaignBehavior
	{
		get
		{
			if (_allianceCampaignBehavior == null)
			{
				_allianceCampaignBehavior = Campaign.Current.GetCampaignBehavior<IAllianceCampaignBehavior>();
			}
			return _allianceCampaignBehavior;
		}
	}

	internal static void AutoGeneratedStaticCollectObjectsStartAllianceDecision(object o, List<object> collectedObjects)
	{
		((StartAllianceDecision)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(KingdomToStartAllianceWith);
	}

	internal static object AutoGeneratedGetMemberValueKingdomToStartAllianceWith(object o)
	{
		return ((StartAllianceDecision)o).KingdomToStartAllianceWith;
	}

	public StartAllianceDecision(Clan proposerClan, Kingdom kingdomToStartAllianceWith)
		: base(proposerClan)
	{
		KingdomToStartAllianceWith = kingdomToStartAllianceWith;
	}

	public static Clan GetProposerClanForPlayerKingdom(Kingdom target)
	{
		if (Clan.PlayerClan.Kingdom == null)
		{
			return null;
		}
		TextObject explanation;
		Clan clan = ((Clan.PlayerClan.Kingdom.RulingClan != Clan.PlayerClan && Campaign.Current.Models.AllianceModel.GetScoreOfStartingAlliance(Clan.PlayerClan.Kingdom, target, Clan.PlayerClan.Kingdom.RulingClan, out explanation).ResultNumber > 50f) ? Clan.PlayerClan.Kingdom.RulingClan : null);
		if (clan == null)
		{
			TextObject explanation2;
			List<Clan> list = Clan.PlayerClan.Kingdom.Clans.Where((Clan x) => !x.IsUnderMercenaryService && x != Clan.PlayerClan && Campaign.Current.Models.AllianceModel.GetScoreOfStartingAlliance(Clan.PlayerClan.Kingdom, target, x, out explanation2).ResultNumber > 50f).ToList();
			clan = ((list.Count <= 0) ? Clan.PlayerClan : TaleWorlds.Core.Extensions.MaxBy(list, (Clan x) => Campaign.Current.Models.AllianceModel.GetScoreOfStartingAlliance(Clan.PlayerClan.Kingdom, target, x, out explanation2).ResultNumber));
		}
		return clan;
	}

	public override bool IsAllowed()
	{
		TextObject reason;
		return Campaign.Current.Models.KingdomDecisionPermissionModel.IsStartAllianceDecisionAllowedBetweenKingdoms(base.Kingdom, KingdomToStartAllianceWith, out reason);
	}

	public override int GetProposalInfluenceCost()
	{
		return Campaign.Current.Models.AllianceModel.GetInfluenceCostOfProposingStartingAlliance(base.ProposerClan);
	}

	public override TextObject GetGeneralTitle()
	{
		TextObject textObject = new TextObject("{=aE7OQDMS}Form alliance with the {KINGDOM_NAME}.");
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetSupportTitle()
	{
		TextObject textObject = new TextObject("{=iOmgCFDI}Vote to form an alliance with the {KINGDOM_NAME}.");
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetChooseTitle()
	{
		TextObject textObject = new TextObject("{=KlATZEbb}Forming an Alliance with the {KINGDOM_NAME}.");
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetSupportDescription()
	{
		TextObject textObject = new TextObject("{=wijL0mTy}{FACTION_LEADER} will decide if an alliance will be formed with the {KINGDOM_NAME}. You can pick your stance regarding this decision.");
		textObject.SetTextVariable("FACTION_LEADER", DetermineChooser().Leader.Name);
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override TextObject GetChooseDescription()
	{
		TextObject textObject = new TextObject("{=eAhgrwkZ}As {RULER_NAME_AND_TITLE}, you must decide if an alliance will be formed with the {KINGDOM_NAME}.");
		textObject.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject);
		textObject.SetTextVariable("RULER_NAME_AND_TITLE", GameTexts.FindText("str_faction_ruler_name_with_title", base.Kingdom.Culture.StringId));
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.InformalName);
		return textObject;
	}

	public override IEnumerable<DecisionOutcome> DetermineInitialCandidates()
	{
		yield return new StartAllianceDecisionOutcome(shouldAllianceBeStarted: true, base.Kingdom, KingdomToStartAllianceWith);
		yield return new StartAllianceDecisionOutcome(shouldAllianceBeStarted: false, base.Kingdom, KingdomToStartAllianceWith);
	}

	public override Clan DetermineChooser()
	{
		return base.Kingdom.RulingClan;
	}

	protected override bool ShouldBeCancelledInternal()
	{
		TextObject reason;
		return !CanMakeDecision(out reason);
	}

	public override void DetermineSponsors(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
	{
		foreach (DecisionOutcome possibleOutcome in possibleOutcomes)
		{
			if (((StartAllianceDecisionOutcome)possibleOutcome).ShouldAllianceBeStarted)
			{
				possibleOutcome.SetSponsor(base.ProposerClan);
			}
			else
			{
				AssignDefaultSponsor(possibleOutcome);
			}
		}
	}

	public override void ApplyChosenOutcome(DecisionOutcome chosenOutcome)
	{
		if (((StartAllianceDecisionOutcome)chosenOutcome).ShouldAllianceBeStarted)
		{
			AllianceCampaignBehavior.StartAlliance(base.Kingdom, KingdomToStartAllianceWith);
		}
	}

	public override bool OnShowDecision()
	{
		if (KingdomToStartAllianceWith == Clan.PlayerClan.Kingdom && !Hero.MainHero.Clan.IsUnderMercenaryService)
		{
			AllianceCampaignBehavior.OnAllianceOfferedToPlayerKingdom(base.Kingdom);
			return false;
		}
		return true;
	}

	public override void ApplySecondaryEffects(MBReadOnlyList<DecisionOutcome> possibleOutcomes, DecisionOutcome chosenOutcome)
	{
	}

	public override TextObject GetSecondaryEffects()
	{
		return new TextObject("{=!}All supporters gains some relation with each other.");
	}

	public override TextObject GetChosenOutcomeText(DecisionOutcome chosenOutcome, SupportStatus supportStatus, bool isShortVersion = false)
	{
		TextObject textObject = (((StartAllianceDecisionOutcome)chosenOutcome).ShouldAllianceBeStarted ? (IsSingleClanDecision() ? new TextObject("{=INfHUqxT}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME}.") : (supportStatus switch
		{
			SupportStatus.Majority => new TextObject("{=FNCq25P1}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} with the support of {?RULER.GENDER}her{?}his{\\?} council."), 
			SupportStatus.Minority => new TextObject("{=bYmc9fi3}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} despite the opposition of {?RULER.GENDER}her{?}his{\\?} council."), 
			_ => new TextObject("{=izwKmH2I}{RULER.NAME} has decided to form an alliance with the {KINGDOM_NAME} with the support of half of {?RULER.GENDER}her{?}his{\\?} council."), 
		})) : (IsSingleClanDecision() ? new TextObject("{=o4IxXHnB}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME}.") : (supportStatus switch
		{
			SupportStatus.Majority => new TextObject("{=bR7MIkFi}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} with the support of {?RULER.GENDER}her{?}his{\\?} council."), 
			SupportStatus.Minority => new TextObject("{=F7CMsDyG}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} despite the opposition of {?RULER.GENDER}her{?}his{\\?} council."), 
			_ => new TextObject("{=jaioXYDc}{RULER.NAME} has decided against forming an alliance with the {KINGDOM_NAME} with the support of half of {?RULER.GENDER}her{?}his{\\?} council."), 
		})));
		StringHelpers.SetCharacterProperties("RULER", base.Kingdom.Leader.CharacterObject, textObject);
		textObject.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
		return textObject;
	}

	public override DecisionOutcome GetQueriedDecisionOutcome(MBReadOnlyList<DecisionOutcome> possibleOutcomes)
	{
		return possibleOutcomes.FirstOrDefault((DecisionOutcome t) => ((StartAllianceDecisionOutcome)t).ShouldAllianceBeStarted);
	}

	public float CalculateSupport(Clan clan, out TextObject hint)
	{
		return DetermineSupport(clan, new StartAllianceDecisionOutcome(shouldAllianceBeStarted: true, base.Kingdom, KingdomToStartAllianceWith), out hint);
	}

	public override float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome)
	{
		TextObject hint;
		return DetermineSupport(clan, possibleOutcome, out hint);
	}

	private float DetermineSupport(Clan clan, DecisionOutcome possibleOutcome, out TextObject hint)
	{
		hint = TextObject.GetEmpty();
		if (clan == Clan.PlayerClan)
		{
			return 100f;
		}
		StartAllianceDecisionOutcome obj = (StartAllianceDecisionOutcome)possibleOutcome;
		float resultNumber = Campaign.Current.Models.AllianceModel.GetScoreOfStartingAlliance(base.Kingdom, KingdomToStartAllianceWith, clan, out hint, includeDescription: true).ResultNumber;
		if (obj.ShouldAllianceBeStarted)
		{
			int num = -clan.Leader.GetTraitLevel(DefaultTraits.Valor) * 10 + clan.Leader.GetTraitLevel(DefaultTraits.Calculating) * 10;
			return resultNumber + (float)num;
		}
		float num2 = 0f - resultNumber;
		int num3 = clan.Leader.GetTraitLevel(DefaultTraits.Valor) * 10 - clan.Leader.GetTraitLevel(DefaultTraits.Calculating) * 10;
		return num2 + (float)num3;
	}

	public override bool CanMakeDecision(out TextObject reason)
	{
		if (KingdomToStartAllianceWith.IsEliminated || base.Kingdom.IsEliminated)
		{
			reason = new TextObject("{=a5EAl1aW}That realm has been eliminated.");
			return false;
		}
		if (KingdomToStartAllianceWith == base.Kingdom)
		{
			reason = new TextObject("{=zPoS5fIu}You are referring to your own realm.");
			return false;
		}
		if (KingdomToStartAllianceWith.IsAtWarWith(base.Kingdom))
		{
			reason = new TextObject("{=lseJ70y0}Your realm is at war with the {KINGDOM_NAME}.");
			reason.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
			return false;
		}
		if (base.Kingdom.AlliedKingdoms.Count >= Campaign.Current.Models.AllianceModel.MaxNumberOfAlliances)
		{
			reason = new TextObject("{=plzVaezP}Your realm cannot have any more allies.");
			return false;
		}
		if (KingdomToStartAllianceWith.AlliedKingdoms.Count >= Campaign.Current.Models.AllianceModel.MaxNumberOfAlliances)
		{
			reason = new TextObject("{=rYssCdQb}{KINGDOM_NAME} cannot have any more allies.");
			reason.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
			return false;
		}
		if (KingdomToStartAllianceWith.IsAllyWith(base.Kingdom))
		{
			reason = new TextObject("{=zd9sawl9}You are already allied with the {KINGDOM_NAME}.");
			reason.SetTextVariable("KINGDOM_NAME", KingdomToStartAllianceWith.Name);
			return false;
		}
		StartAllianceDecision startAllianceDecision = new StartAllianceDecision(base.ProposerClan, KingdomToStartAllianceWith);
		TextObject hint;
		float num = startAllianceDecision.CalculateSupport(base.ProposerClan, out hint);
		StartAllianceDecision startAllianceDecision2 = new StartAllianceDecision(KingdomToStartAllianceWith.RulingClan, base.Kingdom);
		startAllianceDecision2.CalculateSupport(KingdomToStartAllianceWith.RulingClan, out var hint2);
		float likelihoodForSponsor = new KingdomElection(startAllianceDecision2).GetLikelihoodForSponsor(KingdomToStartAllianceWith.RulingClan);
		if (num > 50f)
		{
			if (Clan.PlayerClan.Kingdom == KingdomToStartAllianceWith && KingdomToStartAllianceWith.Clans.Count == 1)
			{
				reason = TextObject.GetEmpty();
				return true;
			}
			if (likelihoodForSponsor > 0.5f)
			{
				if (Clan.PlayerClan.Kingdom == base.Kingdom && base.Kingdom.Clans.Count == 1)
				{
					reason = TextObject.GetEmpty();
					return true;
				}
				KingdomElection kingdomElection = new KingdomElection(startAllianceDecision);
				float num2 = 0f;
				foreach (DecisionOutcome possibleOutcome in kingdomElection.PossibleOutcomes)
				{
					if (possibleOutcome is StartAllianceDecisionOutcome { ShouldAllianceBeStarted: not false } startAllianceDecisionOutcome)
					{
						num2 = startAllianceDecisionOutcome.Likelihood;
						break;
					}
				}
				if (num2 > 0.5f)
				{
					reason = TextObject.GetEmpty();
					return true;
				}
			}
		}
		reason = hint2;
		return false;
	}
}
