using System.Collections.Generic;
using System.Linq;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Election;
using TaleWorlds.Library;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.CampaignBehaviors;

public class TradeAgreementsCampaignBehavior : CampaignBehaviorBase, ITradeAgreementsCampaignBehavior
{
	public class TradeAgreementsCampaignBehaviorTypeDefiner : SaveableTypeDefiner
	{
		public TradeAgreementsCampaignBehaviorTypeDefiner()
			: base(312260)
		{
		}

		protected override void DefineStructTypes()
		{
			AddStructDefinition(typeof(TradeAgreement), 1);
		}

		protected override void DefineContainerDefinitions()
		{
			ConstructContainerDefinition(typeof(List<TradeAgreement>));
		}
	}

	internal readonly struct TradeAgreement
	{
		[SaveableField(1)]
		public readonly Kingdom Kingdom1;

		[SaveableField(2)]
		public readonly Kingdom Kingdom2;

		[SaveableField(3)]
		public readonly CampaignTime EndTime;

		public TradeAgreement(Kingdom kingdom1, Kingdom kingdom2, CampaignTime endTime)
		{
			this = default(TradeAgreement);
			Kingdom1 = kingdom1;
			Kingdom2 = kingdom2;
			EndTime = endTime;
		}

		public static void AutoGeneratedStaticCollectObjectsTradeAgreement(object o, List<object> collectedObjects)
		{
			((TradeAgreement)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
		}

		private void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
		{
			collectedObjects.Add(Kingdom1);
			collectedObjects.Add(Kingdom2);
			CampaignTime.AutoGeneratedStaticCollectObjectsCampaignTime(EndTime, collectedObjects);
		}

		internal static object AutoGeneratedGetMemberValueKingdom1(object o)
		{
			return ((TradeAgreement)o).Kingdom1;
		}

		internal static object AutoGeneratedGetMemberValueKingdom2(object o)
		{
			return ((TradeAgreement)o).Kingdom2;
		}

		internal static object AutoGeneratedGetMemberValueEndTime(object o)
		{
			return ((TradeAgreement)o).EndTime;
		}
	}

	private List<TradeAgreement> _tradeAgreements = new List<TradeAgreement>();

	public override void RegisterEvents()
	{
		CampaignEvents.KingdomDestroyedEvent.AddNonSerializedListener(this, OnKingdomDestroyed);
		CampaignEvents.WarDeclared.AddNonSerializedListener(this, WarDeclared);
	}

	public void OnTradeAgreementOfferedToPlayer(Kingdom fromKingdom)
	{
		if (!Clan.PlayerClan.IsUnderMercenaryService)
		{
			KingdomDecision kingdomDecision = Clan.PlayerClan.Kingdom.UnresolvedDecisions.FirstOrDefault((KingdomDecision s) => s is TradeAgreementDecision tradeAgreementDecision && tradeAgreementDecision.TargetKingdom == fromKingdom);
			if (kingdomDecision != null)
			{
				Clan.PlayerClan.Kingdom.RemoveDecision(kingdomDecision);
			}
			Clan.PlayerClan.Kingdom.AddDecision(new TradeAgreementDecision(TradeAgreementDecision.GetProposerClanForPlayerKingdom(fromKingdom), fromKingdom), ignoreInfluenceCost: true);
		}
		else
		{
			AcceptOffer(fromKingdom);
		}
	}

	private void AcceptOffer(Kingdom fromKingdom)
	{
		MakeTradeAgreement(fromKingdom, Clan.PlayerClan.Kingdom, Campaign.Current.Models.TradeAgreementModel.GetTradeAgreementDurationInYears(fromKingdom, Clan.PlayerClan.Kingdom));
	}

	private void WarDeclared(IFaction faction1, IFaction faction2, DeclareWarAction.DeclareWarDetail detail)
	{
		if (faction1 is Kingdom kingdom && faction2 is Kingdom kingdom2 && HasTradeAgreement(kingdom, kingdom2))
		{
			EndTradeAgreement(kingdom, kingdom2);
		}
	}

	private void OnKingdomDestroyed(Kingdom kingdom)
	{
		EndTradeAgreementsOfKingdom(kingdom);
	}

	public override void SyncData(IDataStore dataStore)
	{
		dataStore.SyncData("_tradeAgreements", ref _tradeAgreements);
	}

	public void MakeTradeAgreement(Kingdom kingdom1, Kingdom kingdom2, CampaignTime duration)
	{
		Debug.Print($"Trade agreement signed between {kingdom1.Name} and {kingdom2.Name}");
		TradeAgreement item = new TradeAgreement(kingdom1, kingdom2, CampaignTime.Now + duration);
		_tradeAgreements.Add(item);
		CampaignEventDispatcher.Instance.OnTradeAgreementSigned(kingdom1, kingdom2);
	}

	public void EndTradeAgreementsOfKingdom(Kingdom kingdom)
	{
		_tradeAgreements.RemoveAll((TradeAgreement t) => t.Kingdom1 == kingdom || t.Kingdom2 == kingdom);
	}

	public void EndTradeAgreement(Kingdom kingdom1, Kingdom kingdom2)
	{
		RemoveTradeAgreement(kingdom1, kingdom2);
	}

	public bool HasTradeAgreement(Kingdom kingdom1, Kingdom kingdom2)
	{
		bool result = false;
		if (TryGetTradeAgreementEndTime(kingdom1, kingdom2, out var endTime))
		{
			if (endTime.IsPast)
			{
				EndTradeAgreement(kingdom1, kingdom2);
			}
			else
			{
				result = true;
			}
		}
		return result;
	}

	public CampaignTime GetTradeAgreementEndDate(Kingdom kingdom1, Kingdom kingdom2)
	{
		if (!TryGetTradeAgreementEndTime(kingdom1, kingdom2, out var endTime))
		{
			Debug.FailedAssert("Cant find trade agreement", "C:\\BuildAgent\\work\\mb3\\Source\\Bannerlord\\TaleWorlds.CampaignSystem\\CampaignBehaviors\\TradeAgreementsCampaignBehavior.cs", "GetTradeAgreementEndDate", 146);
			return CampaignTime.Zero;
		}
		return endTime;
	}

	private int GetTradeAgreementsCount(Kingdom kingdom)
	{
		int num = 0;
		foreach (Kingdom item in Kingdom.All)
		{
			if (kingdom != item && HasTradeAgreement(kingdom, item))
			{
				num++;
			}
		}
		return num;
	}

	private bool TryGetTradeAgreementEndTime(Kingdom kingdom1, Kingdom kingdom2, out CampaignTime endTime)
	{
		bool result = false;
		endTime = CampaignTime.Never;
		foreach (TradeAgreement tradeAgreement in _tradeAgreements)
		{
			if ((tradeAgreement.Kingdom1 == kingdom1 && tradeAgreement.Kingdom2 == kingdom2) || (tradeAgreement.Kingdom2 == kingdom1 && tradeAgreement.Kingdom1 == kingdom2))
			{
				endTime = tradeAgreement.EndTime;
				result = true;
				break;
			}
		}
		return result;
	}

	private void RemoveTradeAgreement(Kingdom kingdom1, Kingdom kingdom2)
	{
		int num = _tradeAgreements.Count - 1;
		while (-1 < num)
		{
			TradeAgreement tradeAgreement = _tradeAgreements[num];
			if ((tradeAgreement.Kingdom1 == kingdom1 && tradeAgreement.Kingdom2 == kingdom2) || (tradeAgreement.Kingdom2 == kingdom1 && tradeAgreement.Kingdom1 == kingdom2))
			{
				_tradeAgreements.RemoveAt(num);
				break;
			}
			num--;
		}
	}
}
