using System.ComponentModel;
using System.Numerics;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;

namespace NavalDLC.GauntletUI.AutoGenerated;

public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_28_ItemTemplate : Widget
{
	private Widget _widget;

	private Widget _widget_0;

	private Widget _widget_1;

	private Widget _widget_1_0;

	private Widget _widget_1_1;

	private Widget _widget_1_1_0;

	private Widget _widget_1_1_1;

	private Widget _widget_1_1_2;

	private Widget _widget_1_1_3;

	private Widget _widget_2;

	private ShipUpgradeSlotBaseVM _datasource_Root;

	private ShipUpgradePieceBaseVM _datasource_Root_SelectedPiece;

	public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_28_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	private VisualDefinition CreateVisualDefinitionShip_Image()
	{
		//IL_0011: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0021: Expected O, but got Unknown
		//IL_002c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0038: Unknown result type (might be due to invalid IL or missing references)
		//IL_003e: Expected O, but got Unknown
		//IL_0049: Unknown result type (might be due to invalid IL or missing references)
		//IL_0055: Unknown result type (might be due to invalid IL or missing references)
		//IL_005b: Expected O, but got Unknown
		//IL_0066: Unknown result type (might be due to invalid IL or missing references)
		//IL_0072: Unknown result type (might be due to invalid IL or missing references)
		//IL_0078: Expected O, but got Unknown
		//IL_0083: Unknown result type (might be due to invalid IL or missing references)
		//IL_008b: Expected O, but got Unknown
		VisualDefinition val = new VisualDefinition("Ship.Image", 0.15f, 0f, (Type)3, (Function)0);
		VisualState val2 = new VisualState("Default");
		val2.SuggestedWidth = 212.1f;
		val.AddVisualState(val2);
		VisualState val3 = new VisualState("Hovered");
		val3.SuggestedWidth = 222.2f;
		val.AddVisualState(val3);
		VisualState val4 = new VisualState("Pressed");
		val4.SuggestedWidth = 202f;
		val.AddVisualState(val4);
		VisualState val5 = new VisualState("Selected");
		val5.SuggestedWidth = 232.3f;
		val.AddVisualState(val5);
		return val;
	}

	public void CreateWidgets()
	{
		//IL_000e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0018: Expected O, but got Unknown
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_003a: Expected O, but got Unknown
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		//IL_005c: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_0096: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a0: Expected O, but got Unknown
		//IL_00b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c2: Expected O, but got Unknown
		//IL_00da: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e4: Expected O, but got Unknown
		//IL_00fc: Unknown result type (might be due to invalid IL or missing references)
		//IL_0106: Expected O, but got Unknown
		//IL_011e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0128: Expected O, but got Unknown
		_widget = (Widget)(object)this;
		_widget_0 = new Widget(((Widget)this).Context);
		_widget.AddChild(_widget_0);
		_widget_1 = new Widget(((Widget)this).Context);
		_widget.AddChild(_widget_1);
		_widget_1_0 = new Widget(((Widget)this).Context);
		_widget_1.AddChild(_widget_1_0);
		_widget_1_1 = new Widget(((Widget)this).Context);
		_widget_1.AddChild(_widget_1_1);
		_widget_1_1_0 = new Widget(((Widget)this).Context);
		_widget_1_1.AddChild(_widget_1_1_0);
		_widget_1_1_1 = new Widget(((Widget)this).Context);
		_widget_1_1.AddChild(_widget_1_1_1);
		_widget_1_1_2 = new Widget(((Widget)this).Context);
		_widget_1_1.AddChild(_widget_1_1_2);
		_widget_1_1_3 = new Widget(((Widget)this).Context);
		_widget_1_1.AddChild(_widget_1_1_3);
		_widget_2 = new Widget(((Widget)this).Context);
		_widget.AddChild(_widget_2);
	}

	public void SetIds()
	{
	}

	public void SetAttributes()
	{
		//IL_0081: Unknown result type (might be due to invalid IL or missing references)
		//IL_0135: Unknown result type (might be due to invalid IL or missing references)
		//IL_02c9: Unknown result type (might be due to invalid IL or missing references)
		((Widget)this).WidthSizePolicy = (SizePolicy)0;
		((Widget)this).HeightSizePolicy = (SizePolicy)0;
		((Widget)this).SuggestedWidth = 9f;
		((Widget)this).SuggestedHeight = 9f;
		((Widget)this).MarginBottom = 3f;
		_widget_0.WidthSizePolicy = (SizePolicy)1;
		_widget_0.HeightSizePolicy = (SizePolicy)1;
		_widget_0.Sprite = ((Widget)this).Context.SpriteData.GetSprite("PortScreen\\upgrade_icon");
		_widget_0.Color = new Color(0f, 0f, 0f, 0.4f);
		_widget_1.WidthSizePolicy = (SizePolicy)1;
		_widget_1.HeightSizePolicy = (SizePolicy)1;
		_widget_1_0.WidthSizePolicy = (SizePolicy)1;
		_widget_1_0.HeightSizePolicy = (SizePolicy)1;
		_widget_1_0.Sprite = ((Widget)this).Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_shadow");
		_widget_1_0.ExtendLeft = 1f;
		_widget_1_0.ExtendRight = 1f;
		_widget_1_0.ExtendTop = 1f;
		_widget_1_0.ExtendBottom = 1f;
		_widget_1_0.Color = new Color(0f, 0f, 0f, 1f);
		_widget_1_1.WidthSizePolicy = (SizePolicy)1;
		_widget_1_1.HeightSizePolicy = (SizePolicy)1;
		_widget_1_1_0.WidthSizePolicy = (SizePolicy)1;
		_widget_1_1_0.HeightSizePolicy = (SizePolicy)1;
		_widget_1_1_0.Sprite = ((Widget)this).Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_bronze");
		_widget_1_1_1.WidthSizePolicy = (SizePolicy)1;
		_widget_1_1_1.HeightSizePolicy = (SizePolicy)1;
		_widget_1_1_1.Sprite = ((Widget)this).Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_silver");
		_widget_1_1_2.WidthSizePolicy = (SizePolicy)1;
		_widget_1_1_2.HeightSizePolicy = (SizePolicy)1;
		_widget_1_1_2.Sprite = ((Widget)this).Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_gold");
		_widget_1_1_3.WidthSizePolicy = (SizePolicy)1;
		_widget_1_1_3.HeightSizePolicy = (SizePolicy)1;
		_widget_1_1_3.Sprite = ((Widget)this).Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_diamond");
		_widget_2.WidthSizePolicy = (SizePolicy)1;
		_widget_2.HeightSizePolicy = (SizePolicy)1;
		_widget_2.Sprite = ((Widget)this).Context.SpriteData.GetSprite("PortScreen\\upgrade_icon_glow");
		_widget_2.ExtendLeft = 2f;
		_widget_2.ExtendRight = 2f;
		_widget_2.ExtendTop = 2f;
		_widget_2.ExtendBottom = 2f;
		_widget_2.Color = new Color(0.9960785f, 0.7568628f, 0.3411765f, 1f);
	}

	public void DestroyDataSource()
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_0376: Unknown result type (might be due to invalid IL or missing references)
		//IL_0380: Expected O, but got Unknown
		//IL_038d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0397: Expected O, but got Unknown
		//IL_03a4: Unknown result type (might be due to invalid IL or missing references)
		//IL_03ae: Expected O, but got Unknown
		//IL_03bb: Unknown result type (might be due to invalid IL or missing references)
		//IL_03c5: Expected O, but got Unknown
		//IL_03d2: Unknown result type (might be due to invalid IL or missing references)
		//IL_03dc: Expected O, but got Unknown
		//IL_03e9: Unknown result type (might be due to invalid IL or missing references)
		//IL_03f3: Expected O, but got Unknown
		//IL_0400: Unknown result type (might be due to invalid IL or missing references)
		//IL_040a: Expected O, but got Unknown
		//IL_0417: Unknown result type (might be due to invalid IL or missing references)
		//IL_0421: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			if (_datasource_Root_SelectedPiece != null)
			{
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
				((PropertyOwnerObject)_widget_1_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_1).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_2).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_3).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_3;
				_datasource_Root_SelectedPiece = null;
			}
			_datasource_Root = null;
		}
	}

	public void SetDataSource(ShipUpgradeSlotBaseVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.HasSelectedPiece = _widget_1.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_0(string propertyName)
	{
		if (propertyName == "IsHidden")
		{
			_datasource_Root.IsChanged = _widget_1_0.IsHidden;
		}
	}

	private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsChanged = _widget_2.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_1_0(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root_SelectedPiece.IsBronzeTier = _widget_1_1_0.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_1_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_1_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root_SelectedPiece.IsSilverTier = _widget_1_1_1.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_1_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_1_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root_SelectedPiece.IsGoldTier = _widget_1_1_2.IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1_1_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1_1_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1_1_3(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root_SelectedPiece.IsDiamondTier = _widget_1_1_3.IsVisible;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "SelectedPiece":
			RefreshDataSource_datasource_Root_SelectedPiece(_datasource_Root.SelectedPiece);
			break;
		case "HasSelectedPiece":
			_widget_1.IsVisible = _datasource_Root.HasSelectedPiece;
			break;
		case "IsChanged":
			_widget_1_0.IsHidden = _datasource_Root.IsChanged;
			_widget_2.IsVisible = _datasource_Root.IsChanged;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_SelectedPiece(string propertyName)
	{
		switch (propertyName)
		{
		case "IsBronzeTier":
			_widget_1_1_0.IsVisible = _datasource_Root_SelectedPiece.IsBronzeTier;
			break;
		case "IsSilverTier":
			_widget_1_1_1.IsVisible = _datasource_Root_SelectedPiece.IsSilverTier;
			break;
		case "IsGoldTier":
			_widget_1_1_2.IsVisible = _datasource_Root_SelectedPiece.IsGoldTier;
			break;
		case "IsDiamondTier":
			_widget_1_1_3.IsVisible = _datasource_Root_SelectedPiece.IsDiamondTier;
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(ShipUpgradeSlotBaseVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_07a1: Unknown result type (might be due to invalid IL or missing references)
		//IL_07ab: Expected O, but got Unknown
		//IL_07b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_07c2: Expected O, but got Unknown
		//IL_07cf: Unknown result type (might be due to invalid IL or missing references)
		//IL_07d9: Expected O, but got Unknown
		//IL_07e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_07f0: Expected O, but got Unknown
		//IL_07fd: Unknown result type (might be due to invalid IL or missing references)
		//IL_0807: Expected O, but got Unknown
		//IL_0814: Unknown result type (might be due to invalid IL or missing references)
		//IL_081e: Expected O, but got Unknown
		//IL_082b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0835: Expected O, but got Unknown
		//IL_0842: Unknown result type (might be due to invalid IL or missing references)
		//IL_084c: Expected O, but got Unknown
		//IL_0376: Unknown result type (might be due to invalid IL or missing references)
		//IL_0380: Expected O, but got Unknown
		//IL_038d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0397: Expected O, but got Unknown
		//IL_03a4: Unknown result type (might be due to invalid IL or missing references)
		//IL_03ae: Expected O, but got Unknown
		//IL_03bb: Unknown result type (might be due to invalid IL or missing references)
		//IL_03c5: Expected O, but got Unknown
		//IL_03d2: Unknown result type (might be due to invalid IL or missing references)
		//IL_03dc: Expected O, but got Unknown
		//IL_03e9: Unknown result type (might be due to invalid IL or missing references)
		//IL_03f3: Expected O, but got Unknown
		//IL_0400: Unknown result type (might be due to invalid IL or missing references)
		//IL_040a: Expected O, but got Unknown
		//IL_0417: Unknown result type (might be due to invalid IL or missing references)
		//IL_0421: Expected O, but got Unknown
		//IL_0b3b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0b45: Expected O, but got Unknown
		//IL_0b52: Unknown result type (might be due to invalid IL or missing references)
		//IL_0b5c: Expected O, but got Unknown
		//IL_0b69: Unknown result type (might be due to invalid IL or missing references)
		//IL_0b73: Expected O, but got Unknown
		//IL_0b80: Unknown result type (might be due to invalid IL or missing references)
		//IL_0b8a: Expected O, but got Unknown
		//IL_0b97: Unknown result type (might be due to invalid IL or missing references)
		//IL_0ba1: Expected O, but got Unknown
		//IL_0bae: Unknown result type (might be due to invalid IL or missing references)
		//IL_0bb8: Expected O, but got Unknown
		//IL_0bc5: Unknown result type (might be due to invalid IL or missing references)
		//IL_0bcf: Expected O, but got Unknown
		//IL_0bdc: Unknown result type (might be due to invalid IL or missing references)
		//IL_0be6: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			if (_datasource_Root_SelectedPiece != null)
			{
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
				((PropertyOwnerObject)_widget_1_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_1).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_2).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_3).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_3;
				_datasource_Root_SelectedPiece = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			_widget_1.IsVisible = _datasource_Root.HasSelectedPiece;
			((PropertyOwnerObject)_widget_1).PropertyChanged += PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged += intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
			_widget_1_0.IsHidden = _datasource_Root.IsChanged;
			((PropertyOwnerObject)_widget_1_0).PropertyChanged += PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).intPropertyChanged += intPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_0;
			((PropertyOwnerObject)_widget_1_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_0;
			_widget_2.IsVisible = _datasource_Root.IsChanged;
			((PropertyOwnerObject)_widget_2).PropertyChanged += PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged += intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2;
			_datasource_Root_SelectedPiece = _datasource_Root.SelectedPiece;
			if (_datasource_Root_SelectedPiece != null)
			{
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
				((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
				_widget_1_1_0.IsVisible = _datasource_Root_SelectedPiece.IsBronzeTier;
				((PropertyOwnerObject)_widget_1_1_0).PropertyChanged += PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_0;
				((PropertyOwnerObject)_widget_1_1_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_0;
				_widget_1_1_1.IsVisible = _datasource_Root_SelectedPiece.IsSilverTier;
				((PropertyOwnerObject)_widget_1_1_1).PropertyChanged += PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_1;
				((PropertyOwnerObject)_widget_1_1_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_1;
				_widget_1_1_2.IsVisible = _datasource_Root_SelectedPiece.IsGoldTier;
				((PropertyOwnerObject)_widget_1_1_2).PropertyChanged += PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_2;
				((PropertyOwnerObject)_widget_1_1_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_2;
				_widget_1_1_3.IsVisible = _datasource_Root_SelectedPiece.IsDiamondTier;
				((PropertyOwnerObject)_widget_1_1_3).PropertyChanged += PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_3;
				((PropertyOwnerObject)_widget_1_1_3).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_3;
			}
		}
	}

	private void RefreshDataSource_datasource_Root_SelectedPiece(ShipUpgradePieceBaseVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_0464: Unknown result type (might be due to invalid IL or missing references)
		//IL_046e: Expected O, but got Unknown
		//IL_047b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0485: Expected O, but got Unknown
		//IL_0492: Unknown result type (might be due to invalid IL or missing references)
		//IL_049c: Expected O, but got Unknown
		//IL_04a9: Unknown result type (might be due to invalid IL or missing references)
		//IL_04b3: Expected O, but got Unknown
		//IL_04c0: Unknown result type (might be due to invalid IL or missing references)
		//IL_04ca: Expected O, but got Unknown
		//IL_04d7: Unknown result type (might be due to invalid IL or missing references)
		//IL_04e1: Expected O, but got Unknown
		//IL_04ee: Unknown result type (might be due to invalid IL or missing references)
		//IL_04f8: Expected O, but got Unknown
		//IL_0505: Unknown result type (might be due to invalid IL or missing references)
		//IL_050f: Expected O, but got Unknown
		if (_datasource_Root_SelectedPiece != null)
		{
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
			((PropertyOwnerObject)_widget_1_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_1).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_2).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_3).PropertyChanged -= PropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1_1_3;
			_datasource_Root_SelectedPiece = null;
		}
		_datasource_Root_SelectedPiece = newDataSource;
		_datasource_Root_SelectedPiece = _datasource_Root.SelectedPiece;
		if (_datasource_Root_SelectedPiece != null)
		{
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_SelectedPiece;
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_SelectedPiece);
			((ViewModel)_datasource_Root_SelectedPiece).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_SelectedPiece);
			_widget_1_1_0.IsVisible = _datasource_Root_SelectedPiece.IsBronzeTier;
			((PropertyOwnerObject)_widget_1_1_0).PropertyChanged += PropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_0;
			((PropertyOwnerObject)_widget_1_1_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_0;
			_widget_1_1_1.IsVisible = _datasource_Root_SelectedPiece.IsSilverTier;
			((PropertyOwnerObject)_widget_1_1_1).PropertyChanged += PropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_1;
			((PropertyOwnerObject)_widget_1_1_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_1;
			_widget_1_1_2.IsVisible = _datasource_Root_SelectedPiece.IsGoldTier;
			((PropertyOwnerObject)_widget_1_1_2).PropertyChanged += PropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_2;
			((PropertyOwnerObject)_widget_1_1_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_2;
			_widget_1_1_3.IsVisible = _datasource_Root_SelectedPiece.IsDiamondTier;
			((PropertyOwnerObject)_widget_1_1_3).PropertyChanged += PropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).intPropertyChanged += intPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1_1_3;
			((PropertyOwnerObject)_widget_1_1_3).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1_1_3;
		}
	}
}
