using System.ComponentModel;
using System.Numerics;
using NavalDLC.GauntletUI.Widgets.Widgets;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;

namespace NavalDLC.GauntletUI.AutoGenerated;

public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_19_PortUpgradePieceVisuals__DependendPrefab : Widget
{
	private Widget _widget;

	private BrushWidget _widget_0;

	private BrushWidget _widget_1;

	private BrushWidget _widget_2;

	private BrushWidget _widget_3;

	private PortPieceImageBrushWidget _widget_4;

	private Widget _widget_5;

	private BrushWidget _widget_5_0;

	private BrushWidget _widget_5_1;

	private BrushWidget _widget_5_2;

	private BrushWidget _widget_5_3;

	private Widget _widget_6;

	private BrushWidget _widget_6_0;

	private BrushWidget _widget_6_1;

	private BrushWidget _widget_6_2;

	private BrushWidget _widget_6_3;

	private ShipUpgradePieceBaseVM _datasource_Root;

	public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_19_PortUpgradePieceVisuals__DependendPrefab(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		//IL_000e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0018: Expected O, but got Unknown
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_003a: Expected O, but got Unknown
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		//IL_005c: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_00b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c2: Expected O, but got Unknown
		//IL_00da: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e4: Expected O, but got Unknown
		//IL_00fc: Unknown result type (might be due to invalid IL or missing references)
		//IL_0106: Expected O, but got Unknown
		//IL_011e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0128: Expected O, but got Unknown
		//IL_0140: Unknown result type (might be due to invalid IL or missing references)
		//IL_014a: Expected O, but got Unknown
		//IL_0162: Unknown result type (might be due to invalid IL or missing references)
		//IL_016c: Expected O, but got Unknown
		//IL_0184: Unknown result type (might be due to invalid IL or missing references)
		//IL_018e: Expected O, but got Unknown
		//IL_01a6: Unknown result type (might be due to invalid IL or missing references)
		//IL_01b0: Expected O, but got Unknown
		//IL_01c8: Unknown result type (might be due to invalid IL or missing references)
		//IL_01d2: Expected O, but got Unknown
		//IL_01ea: Unknown result type (might be due to invalid IL or missing references)
		//IL_01f4: Expected O, but got Unknown
		_widget = (Widget)(object)this;
		_widget_0 = new BrushWidget(((Widget)this).Context);
		_widget.AddChild((Widget)(object)_widget_0);
		_widget_1 = new BrushWidget(((Widget)this).Context);
		_widget.AddChild((Widget)(object)_widget_1);
		_widget_2 = new BrushWidget(((Widget)this).Context);
		_widget.AddChild((Widget)(object)_widget_2);
		_widget_3 = new BrushWidget(((Widget)this).Context);
		_widget.AddChild((Widget)(object)_widget_3);
		_widget_4 = new PortPieceImageBrushWidget(((Widget)this).Context);
		_widget.AddChild((Widget)(object)_widget_4);
		_widget_5 = new Widget(((Widget)this).Context);
		_widget.AddChild(_widget_5);
		_widget_5_0 = new BrushWidget(((Widget)this).Context);
		_widget_5.AddChild((Widget)(object)_widget_5_0);
		_widget_5_1 = new BrushWidget(((Widget)this).Context);
		_widget_5.AddChild((Widget)(object)_widget_5_1);
		_widget_5_2 = new BrushWidget(((Widget)this).Context);
		_widget_5.AddChild((Widget)(object)_widget_5_2);
		_widget_5_3 = new BrushWidget(((Widget)this).Context);
		_widget_5.AddChild((Widget)(object)_widget_5_3);
		_widget_6 = new Widget(((Widget)this).Context);
		_widget.AddChild(_widget_6);
		_widget_6_0 = new BrushWidget(((Widget)this).Context);
		_widget_6.AddChild((Widget)(object)_widget_6_0);
		_widget_6_1 = new BrushWidget(((Widget)this).Context);
		_widget_6.AddChild((Widget)(object)_widget_6_1);
		_widget_6_2 = new BrushWidget(((Widget)this).Context);
		_widget_6.AddChild((Widget)(object)_widget_6_2);
		_widget_6_3 = new BrushWidget(((Widget)this).Context);
		_widget_6.AddChild((Widget)(object)_widget_6_3);
	}

	public void SetIds()
	{
	}

	public void SetAttributes()
	{
		((Widget)this).WidthSizePolicy = (SizePolicy)1;
		((Widget)this).HeightSizePolicy = (SizePolicy)1;
		((Widget)this).UpdateChildrenStates = true;
		((Widget)_widget_0).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_0).HeightSizePolicy = (SizePolicy)1;
		_widget_0.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Background.Bronze");
		((Widget)_widget_1).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_1).HeightSizePolicy = (SizePolicy)1;
		_widget_1.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Background.Silver");
		((Widget)_widget_2).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_2).HeightSizePolicy = (SizePolicy)1;
		_widget_2.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Background.Gold");
		((Widget)_widget_3).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_3).HeightSizePolicy = (SizePolicy)1;
		_widget_3.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Background.Diamond");
		((Widget)_widget_4).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_4).HeightSizePolicy = (SizePolicy)1;
		((Widget)_widget_4).MarginLeft = 2f;
		((Widget)_widget_4).MarginRight = 2f;
		((Widget)_widget_4).MarginTop = 2f;
		((Widget)_widget_4).MarginBottom = 2f;
		((BrushWidget)_widget_4).Brush = ((Widget)this).Context.GetBrush("Port.ShipUpgrade.Image");
		_widget_5.WidthSizePolicy = (SizePolicy)1;
		_widget_5.HeightSizePolicy = (SizePolicy)1;
		_widget_5.UpdateChildrenStates = true;
		_widget_5.IsHidden = false;
		((Widget)_widget_5_0).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_5_0).HeightSizePolicy = (SizePolicy)1;
		_widget_5_0.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Frame.Bronze");
		((Widget)_widget_5_1).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_5_1).HeightSizePolicy = (SizePolicy)1;
		_widget_5_1.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Frame.Silver");
		((Widget)_widget_5_2).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_5_2).HeightSizePolicy = (SizePolicy)1;
		_widget_5_2.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Frame.Gold");
		((Widget)_widget_5_3).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_5_3).HeightSizePolicy = (SizePolicy)1;
		_widget_5_3.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.Frame.Diamond");
		_widget_6.WidthSizePolicy = (SizePolicy)1;
		_widget_6.HeightSizePolicy = (SizePolicy)1;
		_widget_6.UpdateChildrenStates = true;
		_widget_6.IsVisible = false;
		((Widget)_widget_6_0).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_6_0).HeightSizePolicy = (SizePolicy)1;
		_widget_6_0.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Bronze");
		((Widget)_widget_6_1).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_6_1).HeightSizePolicy = (SizePolicy)1;
		_widget_6_1.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Silver");
		((Widget)_widget_6_2).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_6_2).HeightSizePolicy = (SizePolicy)1;
		_widget_6_2.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Gold");
		((Widget)_widget_6_3).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_6_3).HeightSizePolicy = (SizePolicy)1;
		_widget_6_3.Brush = ((Widget)this).Context.GetBrush("Port.Slot.Button.UpgradePiece.Frame.Diamond");
	}

	public void DestroyDataSource()
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget_0).PropertyChanged -= PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_3).PropertyChanged -= PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_4).PropertyChanged -= PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).intPropertyChanged -= intPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_5_0).PropertyChanged -= PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_1).PropertyChanged -= PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_2).PropertyChanged -= PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_3).PropertyChanged -= PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_6_0).PropertyChanged -= PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_1).PropertyChanged -= PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_2).PropertyChanged -= PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_3).PropertyChanged -= PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_3;
			_datasource_Root = null;
		}
	}

	public void SetDataSource(ShipUpgradePieceBaseVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsBronzeTier = ((Widget)_widget_0).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsSilverTier = ((Widget)_widget_1).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsGoldTier = ((Widget)_widget_2).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_3(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsDiamondTier = ((Widget)_widget_3).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_4(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_4(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_4(string propertyName)
	{
		if (propertyName == "Identifier")
		{
			_datasource_Root.Identifier = _widget_4.Identifier;
		}
	}

	private void PropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_5_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_5_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_5_0(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsBronzeTier = ((Widget)_widget_5_0).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_5_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_5_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_5_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsSilverTier = ((Widget)_widget_5_1).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_5_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_5_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_5_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsGoldTier = ((Widget)_widget_5_2).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_5_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_5_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_5_3(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsDiamondTier = ((Widget)_widget_5_3).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_6_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_6_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_6_0(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsBronzeTier = ((Widget)_widget_6_0).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_6_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_6_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_6_1(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsSilverTier = ((Widget)_widget_6_1).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_6_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_6_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_6_2(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsGoldTier = ((Widget)_widget_6_2).IsVisible;
		}
	}

	private void PropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_6_3(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_6_3(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_6_3(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsDiamondTier = ((Widget)_widget_6_3).IsVisible;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "IsBronzeTier":
			((Widget)_widget_0).IsVisible = _datasource_Root.IsBronzeTier;
			((Widget)_widget_5_0).IsVisible = _datasource_Root.IsBronzeTier;
			((Widget)_widget_6_0).IsVisible = _datasource_Root.IsBronzeTier;
			break;
		case "IsSilverTier":
			((Widget)_widget_1).IsVisible = _datasource_Root.IsSilverTier;
			((Widget)_widget_5_1).IsVisible = _datasource_Root.IsSilverTier;
			((Widget)_widget_6_1).IsVisible = _datasource_Root.IsSilverTier;
			break;
		case "IsGoldTier":
			((Widget)_widget_2).IsVisible = _datasource_Root.IsGoldTier;
			((Widget)_widget_5_2).IsVisible = _datasource_Root.IsGoldTier;
			((Widget)_widget_6_2).IsVisible = _datasource_Root.IsGoldTier;
			break;
		case "IsDiamondTier":
			((Widget)_widget_3).IsVisible = _datasource_Root.IsDiamondTier;
			((Widget)_widget_5_3).IsVisible = _datasource_Root.IsDiamondTier;
			((Widget)_widget_6_3).IsVisible = _datasource_Root.IsDiamondTier;
			break;
		case "Identifier":
			_widget_4.Identifier = _datasource_Root.Identifier;
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(ShipUpgradePieceBaseVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_0b9a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0ba4: Expected O, but got Unknown
		//IL_0bb1: Unknown result type (might be due to invalid IL or missing references)
		//IL_0bbb: Expected O, but got Unknown
		//IL_0bc8: Unknown result type (might be due to invalid IL or missing references)
		//IL_0bd2: Expected O, but got Unknown
		//IL_0bdf: Unknown result type (might be due to invalid IL or missing references)
		//IL_0be9: Expected O, but got Unknown
		//IL_0bf6: Unknown result type (might be due to invalid IL or missing references)
		//IL_0c00: Expected O, but got Unknown
		//IL_0c0d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0c17: Expected O, but got Unknown
		//IL_0c24: Unknown result type (might be due to invalid IL or missing references)
		//IL_0c2e: Expected O, but got Unknown
		//IL_0c3b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0c45: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget_0).PropertyChanged -= PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_3).PropertyChanged -= PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_4).PropertyChanged -= PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).intPropertyChanged -= intPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_5_0).PropertyChanged -= PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_1).PropertyChanged -= PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_2).PropertyChanged -= PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_3).PropertyChanged -= PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_6_0).PropertyChanged -= PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_1).PropertyChanged -= PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_2).PropertyChanged -= PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_3).PropertyChanged -= PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).intPropertyChanged -= intPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_6_3;
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((Widget)_widget_0).IsVisible = _datasource_Root.IsBronzeTier;
			((PropertyOwnerObject)_widget_0).PropertyChanged += PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged += intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0;
			((Widget)_widget_1).IsVisible = _datasource_Root.IsSilverTier;
			((PropertyOwnerObject)_widget_1).PropertyChanged += PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged += intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
			((Widget)_widget_2).IsVisible = _datasource_Root.IsGoldTier;
			((PropertyOwnerObject)_widget_2).PropertyChanged += PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged += intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2;
			((Widget)_widget_3).IsVisible = _datasource_Root.IsDiamondTier;
			((PropertyOwnerObject)_widget_3).PropertyChanged += PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).boolPropertyChanged += boolPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).floatPropertyChanged += floatPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).doublePropertyChanged += doublePropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).intPropertyChanged += intPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).uintPropertyChanged += uintPropertyChangedListenerOf_widget_3;
			((PropertyOwnerObject)_widget_3).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_3;
			_widget_4.Identifier = _datasource_Root.Identifier;
			((PropertyOwnerObject)_widget_4).PropertyChanged += PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).boolPropertyChanged += boolPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).floatPropertyChanged += floatPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).doublePropertyChanged += doublePropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).intPropertyChanged += intPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).uintPropertyChanged += uintPropertyChangedListenerOf_widget_4;
			((PropertyOwnerObject)_widget_4).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_4;
			((Widget)_widget_5_0).IsVisible = _datasource_Root.IsBronzeTier;
			((PropertyOwnerObject)_widget_5_0).PropertyChanged += PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).intPropertyChanged += intPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_5_0;
			((PropertyOwnerObject)_widget_5_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_5_0;
			((Widget)_widget_5_1).IsVisible = _datasource_Root.IsSilverTier;
			((PropertyOwnerObject)_widget_5_1).PropertyChanged += PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).intPropertyChanged += intPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_5_1;
			((PropertyOwnerObject)_widget_5_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_5_1;
			((Widget)_widget_5_2).IsVisible = _datasource_Root.IsGoldTier;
			((PropertyOwnerObject)_widget_5_2).PropertyChanged += PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).intPropertyChanged += intPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_5_2;
			((PropertyOwnerObject)_widget_5_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_5_2;
			((Widget)_widget_5_3).IsVisible = _datasource_Root.IsDiamondTier;
			((PropertyOwnerObject)_widget_5_3).PropertyChanged += PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).boolPropertyChanged += boolPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).floatPropertyChanged += floatPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).doublePropertyChanged += doublePropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).intPropertyChanged += intPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).uintPropertyChanged += uintPropertyChangedListenerOf_widget_5_3;
			((PropertyOwnerObject)_widget_5_3).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_5_3;
			((Widget)_widget_6_0).IsVisible = _datasource_Root.IsBronzeTier;
			((PropertyOwnerObject)_widget_6_0).PropertyChanged += PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).intPropertyChanged += intPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_6_0;
			((PropertyOwnerObject)_widget_6_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_6_0;
			((Widget)_widget_6_1).IsVisible = _datasource_Root.IsSilverTier;
			((PropertyOwnerObject)_widget_6_1).PropertyChanged += PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).intPropertyChanged += intPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_6_1;
			((PropertyOwnerObject)_widget_6_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_6_1;
			((Widget)_widget_6_2).IsVisible = _datasource_Root.IsGoldTier;
			((PropertyOwnerObject)_widget_6_2).PropertyChanged += PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).intPropertyChanged += intPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_6_2;
			((PropertyOwnerObject)_widget_6_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_6_2;
			((Widget)_widget_6_3).IsVisible = _datasource_Root.IsDiamondTier;
			((PropertyOwnerObject)_widget_6_3).PropertyChanged += PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).boolPropertyChanged += boolPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).floatPropertyChanged += floatPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).doublePropertyChanged += doublePropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).intPropertyChanged += intPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).uintPropertyChanged += uintPropertyChangedListenerOf_widget_6_3;
			((PropertyOwnerObject)_widget_6_3).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_6_3;
		}
	}
}
