using System.ComponentModel;
using System.Numerics;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.Library;

namespace NavalDLC.GauntletUI.AutoGenerated;

public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_4_ItemTemplate : PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_22_PortUpgradePiece__InheritedPrefab
{
	private PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_22_PortUpgradePiece__InheritedPrefab _widget;

	private ShipUpgradePieceBaseVM _datasource_Root;

	public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_4_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	private VisualDefinition CreateVisualDefinitionCameraControls()
	{
		//IL_0011: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0021: Expected O, but got Unknown
		//IL_002c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0038: Unknown result type (might be due to invalid IL or missing references)
		//IL_003e: Expected O, but got Unknown
		//IL_0049: Unknown result type (might be due to invalid IL or missing references)
		//IL_0051: Expected O, but got Unknown
		VisualDefinition val = new VisualDefinition("CameraControls", 0.45f, 0f, (Type)2, (Function)4);
		VisualState val2 = new VisualState("Default");
		val2.MarginBottom = 60f;
		val.AddVisualState(val2);
		VisualState val3 = new VisualState("Extended");
		val3.MarginBottom = 96f;
		val.AddVisualState(val3);
		return val;
	}

	private VisualDefinition CreateVisualDefinitionShip_Slot()
	{
		//IL_0011: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0021: Expected O, but got Unknown
		//IL_0037: Unknown result type (might be due to invalid IL or missing references)
		//IL_0043: Unknown result type (might be due to invalid IL or missing references)
		//IL_0049: Expected O, but got Unknown
		//IL_005f: Unknown result type (might be due to invalid IL or missing references)
		//IL_006b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0071: Expected O, but got Unknown
		//IL_0087: Unknown result type (might be due to invalid IL or missing references)
		//IL_0093: Unknown result type (might be due to invalid IL or missing references)
		//IL_0099: Expected O, but got Unknown
		//IL_00af: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b7: Expected O, but got Unknown
		VisualDefinition val = new VisualDefinition("Ship.Slot", 0.15f, 0f, (Type)3, (Function)0);
		VisualState val2 = new VisualState("Default");
		val2.SuggestedWidth = 70f;
		val2.SuggestedHeight = 70f;
		val.AddVisualState(val2);
		VisualState val3 = new VisualState("Hovered");
		val3.SuggestedWidth = 71.75f;
		val3.SuggestedHeight = 71.75f;
		val.AddVisualState(val3);
		VisualState val4 = new VisualState("Pressed");
		val4.SuggestedWidth = 68.25f;
		val4.SuggestedHeight = 68.25f;
		val.AddVisualState(val4);
		VisualState val5 = new VisualState("Selected");
		val5.SuggestedWidth = 73.5f;
		val5.SuggestedHeight = 73.5f;
		val.AddVisualState(val5);
		return val;
	}

	public override void CreateWidgets()
	{
		base.CreateWidgets();
		_widget = this;
	}

	public override void SetIds()
	{
		base.SetIds();
	}

	public override void SetAttributes()
	{
		base.SetAttributes();
		((Widget)this).WidthSizePolicy = (SizePolicy)0;
		((Widget)this).HeightSizePolicy = (SizePolicy)0;
		((Widget)this).SuggestedWidth = 70f;
		((Widget)this).SuggestedHeight = 70f;
		((Widget)this).MarginBottom = 14f;
		((Widget)this).MarginRight = 14f;
	}

	public override void DestroyDataSource()
	{
		//IL_0035: Unknown result type (might be due to invalid IL or missing references)
		//IL_003f: Expected O, but got Unknown
		//IL_004c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0056: Expected O, but got Unknown
		//IL_0063: Unknown result type (might be due to invalid IL or missing references)
		//IL_006d: Expected O, but got Unknown
		//IL_007a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0084: Expected O, but got Unknown
		//IL_0091: Unknown result type (might be due to invalid IL or missing references)
		//IL_009b: Expected O, but got Unknown
		//IL_00a8: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b2: Expected O, but got Unknown
		//IL_00bf: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c9: Expected O, but got Unknown
		//IL_00d6: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e0: Expected O, but got Unknown
		base.DestroyDataSource();
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget).PropertyChanged -= PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged -= intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_datasource_Root = null;
		}
	}

	public override void SetDataSource(ShipUpgradePieceBaseVM dataSource)
	{
		base.SetDataSource(dataSource);
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		if (propertyName == "IsVisible")
		{
			_datasource_Root.IsGoldTier = ((Widget)_widget).IsVisible;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		if (propertyName == "IsGoldTier")
		{
			((Widget)_widget).IsVisible = _datasource_Root.IsGoldTier;
		}
	}

	private void RefreshDataSource_datasource_Root(ShipUpgradePieceBaseVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_01e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_01f0: Expected O, but got Unknown
		//IL_01fd: Unknown result type (might be due to invalid IL or missing references)
		//IL_0207: Expected O, but got Unknown
		//IL_0214: Unknown result type (might be due to invalid IL or missing references)
		//IL_021e: Expected O, but got Unknown
		//IL_022b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0235: Expected O, but got Unknown
		//IL_0242: Unknown result type (might be due to invalid IL or missing references)
		//IL_024c: Expected O, but got Unknown
		//IL_0259: Unknown result type (might be due to invalid IL or missing references)
		//IL_0263: Expected O, but got Unknown
		//IL_0270: Unknown result type (might be due to invalid IL or missing references)
		//IL_027a: Expected O, but got Unknown
		//IL_0287: Unknown result type (might be due to invalid IL or missing references)
		//IL_0291: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget).PropertyChanged -= PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged -= intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((Widget)_widget).IsVisible = _datasource_Root.IsGoldTier;
			((PropertyOwnerObject)_widget).PropertyChanged += PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged += boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged += floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged += doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged += intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged += uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
		}
	}
}
