using System.ComponentModel;
using System.Numerics;
using NavalDLC.ViewModelCollection.Port;
using TaleWorlds.Core.ViewModelCollection.Information;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;

namespace NavalDLC.GauntletUI.AutoGenerated;

public class PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_6_ItemTemplate : ListPanel
{
	private ListPanel _widget;

	private TextWidget _widget_0;

	private TextWidget _widget_1;

	private TextWidget _widget_2;

	private BoolStateChangerWidget _widget_2_0;

	private HintWidget _widget_3;

	private ShipStatVM _datasource_Root;

	private HintViewModel _datasource_Root_Hint;

	public PortScreen__NavalDLC_ViewModelCollection_Port_PortVM_Dependency_6_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	private VisualDefinition CreateVisualDefinitionCameraControls()
	{
		//IL_0011: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0021: Expected O, but got Unknown
		//IL_002c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0038: Unknown result type (might be due to invalid IL or missing references)
		//IL_003e: Expected O, but got Unknown
		//IL_0049: Unknown result type (might be due to invalid IL or missing references)
		//IL_0051: Expected O, but got Unknown
		VisualDefinition val = new VisualDefinition("CameraControls", 0.45f, 0f, (Type)2, (Function)4);
		VisualState val2 = new VisualState("Default");
		val2.MarginBottom = 60f;
		val.AddVisualState(val2);
		VisualState val3 = new VisualState("Extended");
		val3.MarginBottom = 96f;
		val.AddVisualState(val3);
		return val;
	}

	private VisualDefinition CreateVisualDefinitionShip_Slot()
	{
		//IL_0011: Unknown result type (might be due to invalid IL or missing references)
		//IL_001b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0021: Expected O, but got Unknown
		//IL_0037: Unknown result type (might be due to invalid IL or missing references)
		//IL_0043: Unknown result type (might be due to invalid IL or missing references)
		//IL_0049: Expected O, but got Unknown
		//IL_005f: Unknown result type (might be due to invalid IL or missing references)
		//IL_006b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0071: Expected O, but got Unknown
		//IL_0087: Unknown result type (might be due to invalid IL or missing references)
		//IL_0093: Unknown result type (might be due to invalid IL or missing references)
		//IL_0099: Expected O, but got Unknown
		//IL_00af: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b7: Expected O, but got Unknown
		VisualDefinition val = new VisualDefinition("Ship.Slot", 0.15f, 0f, (Type)3, (Function)0);
		VisualState val2 = new VisualState("Default");
		val2.SuggestedWidth = 70f;
		val2.SuggestedHeight = 70f;
		val.AddVisualState(val2);
		VisualState val3 = new VisualState("Hovered");
		val3.SuggestedWidth = 71.75f;
		val3.SuggestedHeight = 71.75f;
		val.AddVisualState(val3);
		VisualState val4 = new VisualState("Pressed");
		val4.SuggestedWidth = 68.25f;
		val4.SuggestedHeight = 68.25f;
		val.AddVisualState(val4);
		VisualState val5 = new VisualState("Selected");
		val5.SuggestedWidth = 73.5f;
		val5.SuggestedHeight = 73.5f;
		val.AddVisualState(val5);
		return val;
	}

	public void CreateWidgets()
	{
		//IL_000e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0018: Expected O, but got Unknown
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_003a: Expected O, but got Unknown
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		//IL_005c: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_0096: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a0: Expected O, but got Unknown
		_widget = (ListPanel)(object)this;
		_widget_0 = new TextWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_0);
		_widget_1 = new TextWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_1);
		_widget_2 = new TextWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_2);
		_widget_2_0 = new BoolStateChangerWidget(((Widget)this).Context);
		((Widget)_widget_2).AddChild((Widget)(object)_widget_2_0);
		_widget_3 = new HintWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_3);
	}

	public void SetIds()
	{
	}

	public void SetAttributes()
	{
		((Widget)this).DoNotPassEventsToChildren = true;
		((Widget)this).WidthSizePolicy = (SizePolicy)1;
		((Widget)this).HeightSizePolicy = (SizePolicy)0;
		((Widget)this).SuggestedHeight = 28f;
		((ListPanel)this).StackLayout.LayoutMethod = (LayoutMethod)0;
		((Widget)_widget_0).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_0).HeightSizePolicy = (SizePolicy)1;
		((Widget)_widget_0).SuggestedWidth = 146f;
		((BrushWidget)_widget_0).Brush = ((Widget)this).Context.GetBrush("Port.Ship.Stat.Name.Text");
		((Widget)_widget_0).MarginRight = 4f;
		((Widget)_widget_1).WidthSizePolicy = (SizePolicy)2;
		((Widget)_widget_1).HeightSizePolicy = (SizePolicy)1;
		((Widget)_widget_1).MaxWidth = 125f;
		((BrushWidget)_widget_1).Brush = ((Widget)this).Context.GetBrush("Port.Ship.Stat.Value.Text");
		((Widget)_widget_1).MarginLeft = 4f;
		((Widget)_widget_2).WidthSizePolicy = (SizePolicy)2;
		((Widget)_widget_2).HeightSizePolicy = (SizePolicy)1;
		((BrushWidget)_widget_2).Brush = ((Widget)this).Context.GetBrush("Port.Ship.Stat.BonusValue.Text");
		((Widget)_widget_2).MarginLeft = 4f;
		_widget_2_0.TrueState = "Positive";
		_widget_2_0.FalseState = "Negative";
		_widget_2_0.TargetWidget = (Widget)(object)_widget_2;
		((Widget)_widget_3).IsEnabled = false;
	}

	public void DestroyDataSource()
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_0445: Unknown result type (might be due to invalid IL or missing references)
		//IL_044f: Expected O, but got Unknown
		//IL_045c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0466: Expected O, but got Unknown
		//IL_0473: Unknown result type (might be due to invalid IL or missing references)
		//IL_047d: Expected O, but got Unknown
		//IL_048a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0494: Expected O, but got Unknown
		//IL_04a1: Unknown result type (might be due to invalid IL or missing references)
		//IL_04ab: Expected O, but got Unknown
		//IL_04b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_04c2: Expected O, but got Unknown
		//IL_04cf: Unknown result type (might be due to invalid IL or missing references)
		//IL_04d9: Expected O, but got Unknown
		//IL_04e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_04f0: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget_0).PropertyChanged -= PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2_0).PropertyChanged -= PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2_0;
			if (_datasource_Root_Hint != null)
			{
				((ViewModel)_datasource_Root_Hint).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint);
				((Widget)_widget_3).EventFire -= EventListenerOf_widget_3;
				_datasource_Root_Hint = null;
			}
			_datasource_Root = null;
		}
	}

	public void SetDataSource(ShipStatVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void EventListenerOf_widget_3(Widget widget, string commandName, object[] args)
	{
		if (commandName == "HoverBegin")
		{
			_datasource_Root_Hint.ExecuteBeginHint();
		}
		if (commandName == "HoverEnd")
		{
			_datasource_Root_Hint.ExecuteEndHint();
		}
	}

	private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.Name = _widget_0.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.ValueText = _widget_1.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.BonusValueText = _widget_2.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2_0(string propertyName)
	{
		if (propertyName == "BooleanCheck")
		{
			_datasource_Root.IsBonusBeneficial = _widget_2_0.BooleanCheck;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "Hint":
			RefreshDataSource_datasource_Root_Hint(_datasource_Root.Hint);
			break;
		case "Name":
			_widget_0.Text = _datasource_Root.Name;
			break;
		case "ValueText":
			_widget_1.Text = _datasource_Root.ValueText;
			break;
		case "BonusValueText":
			_widget_2.Text = _datasource_Root.BonusValueText;
			break;
		case "IsBonusBeneficial":
			_widget_2_0.BooleanCheck = _datasource_Root.IsBonusBeneficial;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Hint(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Hint(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Hint(string propertyName)
	{
	}

	private void RefreshDataSource_datasource_Root(ShipStatVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_054b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0555: Expected O, but got Unknown
		//IL_0562: Unknown result type (might be due to invalid IL or missing references)
		//IL_056c: Expected O, but got Unknown
		//IL_0579: Unknown result type (might be due to invalid IL or missing references)
		//IL_0583: Expected O, but got Unknown
		//IL_0590: Unknown result type (might be due to invalid IL or missing references)
		//IL_059a: Expected O, but got Unknown
		//IL_05a7: Unknown result type (might be due to invalid IL or missing references)
		//IL_05b1: Expected O, but got Unknown
		//IL_05be: Unknown result type (might be due to invalid IL or missing references)
		//IL_05c8: Expected O, but got Unknown
		//IL_05d5: Unknown result type (might be due to invalid IL or missing references)
		//IL_05df: Expected O, but got Unknown
		//IL_05ec: Unknown result type (might be due to invalid IL or missing references)
		//IL_05f6: Expected O, but got Unknown
		//IL_0445: Unknown result type (might be due to invalid IL or missing references)
		//IL_044f: Expected O, but got Unknown
		//IL_045c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0466: Expected O, but got Unknown
		//IL_0473: Unknown result type (might be due to invalid IL or missing references)
		//IL_047d: Expected O, but got Unknown
		//IL_048a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0494: Expected O, but got Unknown
		//IL_04a1: Unknown result type (might be due to invalid IL or missing references)
		//IL_04ab: Expected O, but got Unknown
		//IL_04b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_04c2: Expected O, but got Unknown
		//IL_04cf: Unknown result type (might be due to invalid IL or missing references)
		//IL_04d9: Expected O, but got Unknown
		//IL_04e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_04f0: Expected O, but got Unknown
		//IL_09ca: Unknown result type (might be due to invalid IL or missing references)
		//IL_09d4: Expected O, but got Unknown
		//IL_09e1: Unknown result type (might be due to invalid IL or missing references)
		//IL_09eb: Expected O, but got Unknown
		//IL_09f8: Unknown result type (might be due to invalid IL or missing references)
		//IL_0a02: Expected O, but got Unknown
		//IL_0a0f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0a19: Expected O, but got Unknown
		//IL_0a26: Unknown result type (might be due to invalid IL or missing references)
		//IL_0a30: Expected O, but got Unknown
		//IL_0a3d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0a47: Expected O, but got Unknown
		//IL_0a54: Unknown result type (might be due to invalid IL or missing references)
		//IL_0a5e: Expected O, but got Unknown
		//IL_0a6b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0a75: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget_0).PropertyChanged -= PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2_0).PropertyChanged -= PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2_0;
			if (_datasource_Root_Hint != null)
			{
				((ViewModel)_datasource_Root_Hint).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint);
				((Widget)_widget_3).EventFire -= EventListenerOf_widget_3;
				_datasource_Root_Hint = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			_widget_0.Text = _datasource_Root.Name;
			((PropertyOwnerObject)_widget_0).PropertyChanged += PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged += intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0;
			_widget_1.Text = _datasource_Root.ValueText;
			((PropertyOwnerObject)_widget_1).PropertyChanged += PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged += intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
			_widget_2.Text = _datasource_Root.BonusValueText;
			((PropertyOwnerObject)_widget_2).PropertyChanged += PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged += intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2;
			_widget_2_0.BooleanCheck = _datasource_Root.IsBonusBeneficial;
			((PropertyOwnerObject)_widget_2_0).PropertyChanged += PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).intPropertyChanged += intPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_2_0;
			((PropertyOwnerObject)_widget_2_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2_0;
			_datasource_Root_Hint = _datasource_Root.Hint;
			if (_datasource_Root_Hint != null)
			{
				((ViewModel)_datasource_Root_Hint).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint);
				((ViewModel)_datasource_Root_Hint).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint);
				((Widget)_widget_3).EventFire += EventListenerOf_widget_3;
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Hint(HintViewModel newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_013f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0149: Expected O, but got Unknown
		//IL_0156: Unknown result type (might be due to invalid IL or missing references)
		//IL_0160: Expected O, but got Unknown
		//IL_016d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0177: Expected O, but got Unknown
		//IL_0184: Unknown result type (might be due to invalid IL or missing references)
		//IL_018e: Expected O, but got Unknown
		//IL_019b: Unknown result type (might be due to invalid IL or missing references)
		//IL_01a5: Expected O, but got Unknown
		//IL_01b2: Unknown result type (might be due to invalid IL or missing references)
		//IL_01bc: Expected O, but got Unknown
		//IL_01c9: Unknown result type (might be due to invalid IL or missing references)
		//IL_01d3: Expected O, but got Unknown
		//IL_01e0: Unknown result type (might be due to invalid IL or missing references)
		//IL_01ea: Expected O, but got Unknown
		if (_datasource_Root_Hint != null)
		{
			((ViewModel)_datasource_Root_Hint).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint);
			((Widget)_widget_3).EventFire -= EventListenerOf_widget_3;
			_datasource_Root_Hint = null;
		}
		_datasource_Root_Hint = newDataSource;
		_datasource_Root_Hint = _datasource_Root.Hint;
		if (_datasource_Root_Hint != null)
		{
			((ViewModel)_datasource_Root_Hint).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Hint;
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Hint);
			((ViewModel)_datasource_Root_Hint).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Hint);
			((Widget)_widget_3).EventFire += EventListenerOf_widget_3;
		}
	}
}
