using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Numerics;
using StoryMode.ViewModelCollection.Missions;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.Layout;
using TaleWorlds.Library;

namespace StoryMode.GauntletUI.AutoGenerated;

public class TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_3_TrainingFieldObjectiveItem__InheritedPrefab : ListPanel
{
	private ListPanel _widget;

	private ListPanel _widget_0;

	private ButtonWidget _widget_0_0;

	private ButtonWidget _widget_0_1;

	private TextWidget _widget_0_1_0;

	private ListPanel _widget_1;

	private TrainingFieldObjectiveItemVM _datasource_Root;

	private MBBindingList<TrainingFieldObjectiveItemVM> _datasource_Root_ObjectiveItems;

	public TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_3_TrainingFieldObjectiveItem__InheritedPrefab(UIContext context)
		: base(context)
	{
	}

	public virtual void CreateWidgets()
	{
		//IL_000e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0018: Expected O, but got Unknown
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_003a: Expected O, but got Unknown
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		//IL_005c: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_0096: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a0: Expected O, but got Unknown
		_widget = (ListPanel)(object)this;
		_widget_0 = new ListPanel(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_0);
		_widget_0_0 = new ButtonWidget(((Widget)this).Context);
		((Widget)_widget_0).AddChild((Widget)(object)_widget_0_0);
		_widget_0_1 = new ButtonWidget(((Widget)this).Context);
		((Widget)_widget_0).AddChild((Widget)(object)_widget_0_1);
		_widget_0_1_0 = new TextWidget(((Widget)this).Context);
		((Widget)_widget_0_1).AddChild((Widget)(object)_widget_0_1_0);
		_widget_1 = new ListPanel(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_1);
	}

	public virtual void SetIds()
	{
	}

	public virtual void SetAttributes()
	{
		((Widget)this).MarginLeft = 20f;
		((Widget)this).WidthSizePolicy = (SizePolicy)2;
		((Widget)this).HeightSizePolicy = (SizePolicy)2;
		((ListPanel)this).StackLayout.LayoutMethod = (LayoutMethod)4;
		((Widget)_widget_0).WidthSizePolicy = (SizePolicy)2;
		((Widget)_widget_0).HeightSizePolicy = (SizePolicy)2;
		((Widget)_widget_0).DoNotPassEventsToChildren = true;
		((Widget)_widget_0_0).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_0_0).HeightSizePolicy = (SizePolicy)0;
		((Widget)_widget_0_0).SuggestedWidth = 15f;
		((Widget)_widget_0_0).SuggestedHeight = 15f;
		((BrushWidget)_widget_0_0).Brush = ((Widget)this).Context.GetBrush("Objective.Completion");
		((Widget)_widget_0_0).MarginTop = 5f;
		((Widget)_widget_0_1).WidthSizePolicy = (SizePolicy)2;
		((Widget)_widget_0_1).HeightSizePolicy = (SizePolicy)2;
		((Widget)_widget_0_1).MarginTop = 5f;
		((Widget)_widget_0_1).UpdateChildrenStates = true;
		((Widget)_widget_0_1).MarginLeft = 10f;
		((Widget)_widget_0_1_0).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_0_1_0).HeightSizePolicy = (SizePolicy)2;
		((Widget)_widget_0_1_0).SuggestedWidth = 300f;
		((Widget)_widget_0_1_0).ClipContents = false;
		((BrushWidget)_widget_0_1_0).Brush = ((Widget)this).Context.GetBrush("Objective.Text");
		((Widget)_widget_1).MarginLeft = 20f;
		((Widget)_widget_1).WidthSizePolicy = (SizePolicy)2;
		((Widget)_widget_1).HeightSizePolicy = (SizePolicy)2;
		_widget_1.StackLayout.LayoutMethod = (LayoutMethod)4;
	}

	public virtual void DestroyDataSource()
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_035c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0366: Expected O, but got Unknown
		if (_datasource_Root == null)
		{
			return;
		}
		((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
		((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
		((PropertyOwnerObject)_widget_0_0).PropertyChanged -= PropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_1).PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_0;
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged -= new ListChangedEventHandler(OnList_datasource_Root_ObjectiveItemsChanged);
			for (int num = ((Widget)_widget_1).ChildCount - 1; num >= 0; num--)
			{
				Widget child = ((Widget)_widget_1).GetChild(num);
				((Widget)(TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child).OnBeforeRemovedChild(child);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)((Widget)_widget_1).GetChild(num)).DestroyDataSource();
			}
			_datasource_Root_ObjectiveItems = null;
		}
		_datasource_Root = null;
	}

	public virtual void SetDataSource(TrainingFieldObjectiveItemVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_0(string propertyName)
	{
		if (propertyName == "IsSelected")
		{
			_datasource_Root.IsActive = _widget_0_0.IsSelected;
		}
		else if (propertyName == "IsDisabled")
		{
			_datasource_Root.IsCompleted = ((Widget)_widget_0_0).IsDisabled;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1(string propertyName)
	{
		if (propertyName == "IsSelected")
		{
			_datasource_Root.IsActive = _widget_0_1.IsSelected;
		}
		else if (propertyName == "IsDisabled")
		{
			_datasource_Root.IsCompleted = ((Widget)_widget_0_1).IsDisabled;
		}
	}

	private void PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0_1_0(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.ObjectiveText = _widget_0_1_0.Text;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "ObjectiveItems":
			RefreshDataSource_datasource_Root_ObjectiveItems(_datasource_Root.ObjectiveItems);
			break;
		case "IsActive":
			_widget_0_0.IsSelected = _datasource_Root.IsActive;
			_widget_0_1.IsSelected = _datasource_Root.IsActive;
			break;
		case "IsCompleted":
			((Widget)_widget_0_0).IsDisabled = _datasource_Root.IsCompleted;
			((Widget)_widget_0_1).IsDisabled = _datasource_Root.IsCompleted;
			break;
		case "ObjectiveText":
			_widget_0_1_0.Text = _datasource_Root.ObjectiveText;
			break;
		}
	}

	public void OnList_datasource_Root_ObjectiveItemsChanged(object sender, ListChangedEventArgs e)
	{
		//IL_0001: Unknown result type (might be due to invalid IL or missing references)
		//IL_0006: Unknown result type (might be due to invalid IL or missing references)
		//IL_0007: Unknown result type (might be due to invalid IL or missing references)
		//IL_0025: Expected I4, but got Unknown
		//IL_00e2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e9: Expected O, but got Unknown
		//IL_00ab: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b5: Expected O, but got Unknown
		ListChangedType listChangedType = e.ListChangedType;
		switch ((int)listChangedType)
		{
		case 0:
		{
			for (int num = ((Widget)_widget_1).ChildCount - 1; num >= 0; num--)
			{
				Widget child3 = ((Widget)_widget_1).GetChild(num);
				((Widget)(TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child3).OnBeforeRemovedChild(child3);
				Widget child4 = ((Widget)_widget_1).GetChild(num);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child4).SetDataSource(null);
				((Widget)_widget_1).RemoveChild(child4);
			}
			break;
		}
		case 1:
		{
			for (int i = 0; i < ((Collection<TrainingFieldObjectiveItemVM>)(object)_datasource_Root_ObjectiveItems).Count; i++)
			{
				TrainingFieldObjectiveItemVM bindingObject = ((Collection<TrainingFieldObjectiveItemVM>)(object)_datasource_Root_ObjectiveItems)[i];
				((Widget)_widget_1).FindChild((WidgetSearchDelegate)((Widget widget) => widget.GetComponent<GeneratedWidgetData>().Data == bindingObject)).SetSiblingIndex(i, false);
			}
			break;
		}
		case 2:
		{
			TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate = new TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate(((Widget)this).Context);
			GeneratedWidgetData val = new GeneratedWidgetData((Widget)(object)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate);
			TrainingFieldObjectiveItemVM dataSource = (TrainingFieldObjectiveItemVM)(val.Data = ((Collection<TrainingFieldObjectiveItemVM>)(object)_datasource_Root_ObjectiveItems)[e.NewIndex]);
			((Widget)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate).AddComponent((WidgetComponent)(object)val);
			((Widget)_widget_1).AddChildAtIndex((Widget)(object)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate, e.NewIndex);
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.CreateWidgets();
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetIds();
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetAttributes();
			trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetDataSource(dataSource);
			break;
		}
		case 3:
		{
			Widget child2 = ((Widget)_widget_1).GetChild(e.NewIndex);
			((Widget)(TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child2).OnBeforeRemovedChild(child2);
			break;
		}
		case 4:
		{
			Widget child = ((Widget)_widget_1).GetChild(e.NewIndex);
			((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child).SetDataSource(null);
			((Widget)_widget_1).RemoveChild(child);
			break;
		}
		case 5:
			break;
		}
	}

	private void RefreshDataSource_datasource_Root(TrainingFieldObjectiveItemVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_0400: Unknown result type (might be due to invalid IL or missing references)
		//IL_040a: Expected O, but got Unknown
		//IL_0417: Unknown result type (might be due to invalid IL or missing references)
		//IL_0421: Expected O, but got Unknown
		//IL_042e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0438: Expected O, but got Unknown
		//IL_0445: Unknown result type (might be due to invalid IL or missing references)
		//IL_044f: Expected O, but got Unknown
		//IL_045c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0466: Expected O, but got Unknown
		//IL_0473: Unknown result type (might be due to invalid IL or missing references)
		//IL_047d: Expected O, but got Unknown
		//IL_048a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0494: Expected O, but got Unknown
		//IL_04a1: Unknown result type (might be due to invalid IL or missing references)
		//IL_04ab: Expected O, but got Unknown
		//IL_035c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0366: Expected O, but got Unknown
		//IL_07af: Unknown result type (might be due to invalid IL or missing references)
		//IL_07b9: Expected O, but got Unknown
		//IL_07cc: Unknown result type (might be due to invalid IL or missing references)
		//IL_07d3: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget_0_0).PropertyChanged -= PropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_0;
			((PropertyOwnerObject)_widget_0_1).PropertyChanged -= PropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1;
			((PropertyOwnerObject)_widget_0_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0_1_0;
			((PropertyOwnerObject)_widget_0_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0_1_0;
			if (_datasource_Root_ObjectiveItems != null)
			{
				_datasource_Root_ObjectiveItems.ListChanged -= new ListChangedEventHandler(OnList_datasource_Root_ObjectiveItemsChanged);
				for (int num = ((Widget)_widget_1).ChildCount - 1; num >= 0; num--)
				{
					Widget child = ((Widget)_widget_1).GetChild(num);
					((Widget)(TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child).OnBeforeRemovedChild(child);
					Widget child2 = ((Widget)_widget_1).GetChild(num);
					((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child2).SetDataSource(null);
					((Widget)_widget_1).RemoveChild(child2);
				}
				_datasource_Root_ObjectiveItems = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root == null)
		{
			return;
		}
		((ViewModel)_datasource_Root).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
		((ViewModel)_datasource_Root).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
		((ViewModel)_datasource_Root).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
		_widget_0_0.IsSelected = _datasource_Root.IsActive;
		((Widget)_widget_0_0).IsDisabled = _datasource_Root.IsCompleted;
		((PropertyOwnerObject)_widget_0_0).PropertyChanged += PropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).intPropertyChanged += intPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_0;
		((PropertyOwnerObject)_widget_0_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_0;
		_widget_0_1.IsSelected = _datasource_Root.IsActive;
		((Widget)_widget_0_1).IsDisabled = _datasource_Root.IsCompleted;
		((PropertyOwnerObject)_widget_0_1).PropertyChanged += PropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).intPropertyChanged += intPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1;
		((PropertyOwnerObject)_widget_0_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1;
		_widget_0_1_0.Text = _datasource_Root.ObjectiveText;
		((PropertyOwnerObject)_widget_0_1_0).PropertyChanged += PropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).intPropertyChanged += intPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_0_1_0;
		((PropertyOwnerObject)_widget_0_1_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0_1_0;
		_datasource_Root_ObjectiveItems = _datasource_Root.ObjectiveItems;
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged += new ListChangedEventHandler(OnList_datasource_Root_ObjectiveItemsChanged);
			for (int i = 0; i < ((Collection<TrainingFieldObjectiveItemVM>)(object)_datasource_Root_ObjectiveItems).Count; i++)
			{
				TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate = new TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate(((Widget)this).Context);
				GeneratedWidgetData val = new GeneratedWidgetData((Widget)(object)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate);
				TrainingFieldObjectiveItemVM dataSource = (TrainingFieldObjectiveItemVM)(val.Data = ((Collection<TrainingFieldObjectiveItemVM>)(object)_datasource_Root_ObjectiveItems)[i]);
				((Widget)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate).AddComponent((WidgetComponent)(object)val);
				((Widget)_widget_1).AddChildAtIndex((Widget)(object)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate, i);
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.CreateWidgets();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetIds();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetAttributes();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}

	private void RefreshDataSource_datasource_Root_ObjectiveItems(MBBindingList<TrainingFieldObjectiveItemVM> newDataSource)
	{
		//IL_0015: Unknown result type (might be due to invalid IL or missing references)
		//IL_001f: Expected O, but got Unknown
		//IL_00ac: Unknown result type (might be due to invalid IL or missing references)
		//IL_00b6: Expected O, but got Unknown
		//IL_00c9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00d0: Expected O, but got Unknown
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged -= new ListChangedEventHandler(OnList_datasource_Root_ObjectiveItemsChanged);
			for (int num = ((Widget)_widget_1).ChildCount - 1; num >= 0; num--)
			{
				Widget child = ((Widget)_widget_1).GetChild(num);
				((Widget)(TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child).OnBeforeRemovedChild(child);
				Widget child2 = ((Widget)_widget_1).GetChild(num);
				((TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate)(object)child2).SetDataSource(null);
				((Widget)_widget_1).RemoveChild(child2);
			}
			_datasource_Root_ObjectiveItems = null;
		}
		_datasource_Root_ObjectiveItems = newDataSource;
		_datasource_Root_ObjectiveItems = _datasource_Root.ObjectiveItems;
		if (_datasource_Root_ObjectiveItems != null)
		{
			_datasource_Root_ObjectiveItems.ListChanged += new ListChangedEventHandler(OnList_datasource_Root_ObjectiveItemsChanged);
			for (int i = 0; i < ((Collection<TrainingFieldObjectiveItemVM>)(object)_datasource_Root_ObjectiveItems).Count; i++)
			{
				TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate = new TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate(((Widget)this).Context);
				GeneratedWidgetData val = new GeneratedWidgetData((Widget)(object)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate);
				TrainingFieldObjectiveItemVM dataSource = (TrainingFieldObjectiveItemVM)(val.Data = ((Collection<TrainingFieldObjectiveItemVM>)(object)_datasource_Root_ObjectiveItems)[i]);
				((Widget)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate).AddComponent((WidgetComponent)(object)val);
				((Widget)_widget_1).AddChildAtIndex((Widget)(object)trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate, i);
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.CreateWidgets();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetIds();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetAttributes();
				trainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_4_ItemTemplate.SetDataSource(dataSource);
			}
		}
	}
}
