using System.ComponentModel;
using System.Numerics;
using StoryMode.ViewModelCollection.Missions;
using TaleWorlds.CampaignSystem.ViewModelCollection.Input;
using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.ExtraWidgets;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets.Tutorial;

namespace StoryMode.GauntletUI.AutoGenerated;

public class TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_2_ItemTemplate : TutorialObjectiveItemWidget
{
	private TutorialObjectiveItemWidget _widget;

	private InputKeyVisualWidget _widget_0;

	private TutorialObjectiveMouseParentWidget _widget_1;

	private BrushWidget _widget_1_0;

	private BrushWidget _widget_1_0_0;

	private BrushWidget _widget_1_0_1;

	private BrushWidget _widget_1_0_2;

	private TutorialObjectiveStickParentWidget _widget_2;

	private Widget _widget_2_0;

	private Widget _widget_2_1;

	private TextWidget _widget_2_1_0;

	private TrainingObjectiveKeyVM _datasource_Root;

	private InputKeyItemVM _datasource_Root_Key;

	public TrainingFieldObjectives__StoryMode_ViewModelCollection_Missions_TrainingFieldObjectivesVM_Dependency_2_ItemTemplate(UIContext context)
		: base(context)
	{
	}

	public void CreateWidgets()
	{
		//IL_000e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0018: Expected O, but got Unknown
		//IL_0030: Unknown result type (might be due to invalid IL or missing references)
		//IL_003a: Expected O, but got Unknown
		//IL_0052: Unknown result type (might be due to invalid IL or missing references)
		//IL_005c: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_0096: Unknown result type (might be due to invalid IL or missing references)
		//IL_00a0: Expected O, but got Unknown
		//IL_00b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c2: Expected O, but got Unknown
		//IL_00da: Unknown result type (might be due to invalid IL or missing references)
		//IL_00e4: Expected O, but got Unknown
		//IL_00fc: Unknown result type (might be due to invalid IL or missing references)
		//IL_0106: Expected O, but got Unknown
		//IL_011e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0128: Expected O, but got Unknown
		//IL_0140: Unknown result type (might be due to invalid IL or missing references)
		//IL_014a: Expected O, but got Unknown
		_widget = (TutorialObjectiveItemWidget)(object)this;
		_widget_0 = new InputKeyVisualWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_0);
		_widget_1 = new TutorialObjectiveMouseParentWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_1);
		_widget_1_0 = new BrushWidget(((Widget)this).Context);
		((Widget)_widget_1).AddChild((Widget)(object)_widget_1_0);
		_widget_1_0_0 = new BrushWidget(((Widget)this).Context);
		((Widget)_widget_1_0).AddChild((Widget)(object)_widget_1_0_0);
		_widget_1_0_1 = new BrushWidget(((Widget)this).Context);
		((Widget)_widget_1_0).AddChild((Widget)(object)_widget_1_0_1);
		_widget_1_0_2 = new BrushWidget(((Widget)this).Context);
		((Widget)_widget_1_0).AddChild((Widget)(object)_widget_1_0_2);
		_widget_2 = new TutorialObjectiveStickParentWidget(((Widget)this).Context);
		((Widget)_widget).AddChild((Widget)(object)_widget_2);
		_widget_2_0 = new Widget(((Widget)this).Context);
		((Widget)_widget_2).AddChild(_widget_2_0);
		_widget_2_1 = new Widget(((Widget)this).Context);
		((Widget)_widget_2).AddChild(_widget_2_1);
		_widget_2_1_0 = new TextWidget(((Widget)this).Context);
		_widget_2_1.AddChild((Widget)(object)_widget_2_1_0);
	}

	public void SetIds()
	{
		((Widget)_widget_0).Id = "KeyPressWidget";
		((Widget)_widget_1).Id = "MouseMoveWidget";
		((Widget)_widget_1_0).Id = "MouseParent";
		((Widget)_widget_1_0_0).Id = "LeftClick";
		((Widget)_widget_1_0_1).Id = "RightClick";
		((Widget)_widget_1_0_2).Id = "MiddleClick";
		((Widget)_widget_2).Id = "StickMoveWidget";
		_widget_2_0.Id = "StickBody";
		_widget_2_1.Id = "StickMiddle";
	}

	public void SetAttributes()
	{
		((Widget)this).WidthSizePolicy = (SizePolicy)0;
		((Widget)this).HeightSizePolicy = (SizePolicy)0;
		((Widget)this).SuggestedWidth = 80f;
		((Widget)this).SuggestedHeight = 80f;
		((TutorialObjectiveItemWidget)this).KeyPressWidget = _widget_0;
		((TutorialObjectiveItemWidget)this).MouseMoveWidget = _widget_1;
		((TutorialObjectiveItemWidget)this).StickMoveWidget = _widget_2;
		((Widget)_widget_0).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_0).HeightSizePolicy = (SizePolicy)1;
		((Widget)_widget_1).WidthSizePolicy = (SizePolicy)2;
		((Widget)_widget_1).HeightSizePolicy = (SizePolicy)2;
		_widget_1.MouseBodyWidget = _widget_1_0;
		_widget_1.MouseLeftClickWidget = _widget_1_0_0;
		_widget_1.MouseRightClickWidget = _widget_1_0_1;
		_widget_1.MouseMiddleClickWidget = _widget_1_0_2;
		((Widget)_widget_1).HorizontalAlignment = (HorizontalAlignment)1;
		((Widget)_widget_1).VerticalAlignment = (VerticalAlignment)1;
		((Widget)_widget_1_0).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0).HeightSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0).SuggestedWidth = 65f;
		((Widget)_widget_1_0).SuggestedHeight = 99f;
		_widget_1_0.Brush = ((Widget)this).Context.GetBrush("TrainingField.Mouse.Move");
		((Widget)_widget_1_0).UpdateChildrenStates = true;
		((Widget)_widget_1_0_0).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0_0).HeightSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0_0).SuggestedWidth = 32f;
		((Widget)_widget_1_0_0).SuggestedHeight = 36f;
		_widget_1_0_0.Brush = ((Widget)this).Context.GetBrush("TrainingField.Mouse.Button.Left");
		((Widget)_widget_1_0_0).HorizontalAlignment = (HorizontalAlignment)0;
		((Widget)_widget_1_0_0).VerticalAlignment = (VerticalAlignment)0;
		((Widget)_widget_1_0_0).MarginTop = 1f;
		((Widget)_widget_1_0_0).MarginLeft = 2f;
		((Widget)_widget_1_0_1).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0_1).HeightSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0_1).SuggestedWidth = 32f;
		((Widget)_widget_1_0_1).SuggestedHeight = 36f;
		_widget_1_0_1.Brush = ((Widget)this).Context.GetBrush("TrainingField.Mouse.Button.Right");
		((Widget)_widget_1_0_1).HorizontalAlignment = (HorizontalAlignment)2;
		((Widget)_widget_1_0_1).VerticalAlignment = (VerticalAlignment)0;
		((Widget)_widget_1_0_1).MarginTop = 1f;
		((Widget)_widget_1_0_1).MarginLeft = -2f;
		((Widget)_widget_1_0_2).WidthSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0_2).HeightSizePolicy = (SizePolicy)0;
		((Widget)_widget_1_0_2).SuggestedWidth = 9f;
		((Widget)_widget_1_0_2).SuggestedHeight = 25f;
		_widget_1_0_2.Brush = ((Widget)this).Context.GetBrush("TrainingField.Mouse.Button.Middle");
		((Widget)_widget_1_0_2).HorizontalAlignment = (HorizontalAlignment)1;
		((Widget)_widget_1_0_2).VerticalAlignment = (VerticalAlignment)0;
		((Widget)_widget_1_0_2).MarginTop = 17f;
		((Widget)_widget_1_0_2).AlphaFactor = 0f;
		((Widget)_widget_2).WidthSizePolicy = (SizePolicy)1;
		((Widget)_widget_2).HeightSizePolicy = (SizePolicy)1;
		_widget_2.StickMiddle = _widget_2_1;
		_widget_2_0.WidthSizePolicy = (SizePolicy)0;
		_widget_2_0.HeightSizePolicy = (SizePolicy)0;
		_widget_2_0.SuggestedWidth = 65f;
		_widget_2_0.SuggestedHeight = 65f;
		_widget_2_0.Sprite = ((Widget)this).Context.SpriteData.GetSprite("General\\Mouse\\stick_body");
		_widget_2_0.HorizontalAlignment = (HorizontalAlignment)1;
		_widget_2_0.VerticalAlignment = (VerticalAlignment)1;
		_widget_2_1.WidthSizePolicy = (SizePolicy)0;
		_widget_2_1.HeightSizePolicy = (SizePolicy)0;
		_widget_2_1.SuggestedWidth = 32f;
		_widget_2_1.SuggestedHeight = 32f;
		_widget_2_1.Sprite = ((Widget)this).Context.SpriteData.GetSprite("General\\Mouse\\stick_click");
		_widget_2_1.HorizontalAlignment = (HorizontalAlignment)1;
		_widget_2_1.VerticalAlignment = (VerticalAlignment)1;
		((Widget)_widget_2_1_0).WidthSizePolicy = (SizePolicy)2;
		((Widget)_widget_2_1_0).HeightSizePolicy = (SizePolicy)2;
		((Widget)_widget_2_1_0).HorizontalAlignment = (HorizontalAlignment)1;
		((Widget)_widget_2_1_0).VerticalAlignment = (VerticalAlignment)1;
		((BrushWidget)_widget_2_1_0).Brush = ((Widget)this).Context.GetBrush("Objective.Text");
	}

	public void DestroyDataSource()
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_0445: Unknown result type (might be due to invalid IL or missing references)
		//IL_044f: Expected O, but got Unknown
		//IL_045c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0466: Expected O, but got Unknown
		//IL_0473: Unknown result type (might be due to invalid IL or missing references)
		//IL_047d: Expected O, but got Unknown
		//IL_048a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0494: Expected O, but got Unknown
		//IL_04a1: Unknown result type (might be due to invalid IL or missing references)
		//IL_04ab: Expected O, but got Unknown
		//IL_04b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_04c2: Expected O, but got Unknown
		//IL_04cf: Unknown result type (might be due to invalid IL or missing references)
		//IL_04d9: Expected O, but got Unknown
		//IL_04e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_04f0: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget).PropertyChanged -= PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged -= intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2_1_0;
			if (_datasource_Root_Key != null)
			{
				((ViewModel)_datasource_Root_Key).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Key;
				((ViewModel)_datasource_Root_Key).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Key);
				((PropertyOwnerObject)_widget_0).PropertyChanged -= PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
				_datasource_Root_Key = null;
			}
			_datasource_Root = null;
		}
	}

	public void SetDataSource(TrainingObjectiveKeyVM dataSource)
	{
		RefreshDataSource_datasource_Root(dataSource);
	}

	private void PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void intPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget(string propertyName)
	{
		if (propertyName == "InputType")
		{
			_datasource_Root.InputType = _widget.InputType;
		}
	}

	private void PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_1(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_1(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_1(string propertyName)
	{
		if (propertyName == "KeyId")
		{
			_datasource_Root.ForcedKeyId = _widget_1.KeyId;
		}
		else if (propertyName == "MovementType")
		{
			_datasource_Root.MovementType = _widget_1.MovementType;
		}
	}

	private void PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2(string propertyName)
	{
		if (propertyName == "MovementType")
		{
			_datasource_Root.MovementType = _widget_2.MovementType;
		}
	}

	private void PropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_2_1_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_2_1_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_2_1_0(string propertyName)
	{
		if (propertyName == "Text")
		{
			_datasource_Root.ForcedKeyName = _widget_2_1_0.Text;
		}
	}

	private void PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, object e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void boolPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, bool e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void floatPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, float e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vec2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vec2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void Vector2PropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Vector2 e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void doublePropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, double e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void intPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, int e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void uintPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, uint e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void ColorPropertyChangedListenerOf_widget_0(PropertyOwnerObject propertyOwnerObject, string propertyName, Color e)
	{
		HandleWidgetPropertyChangeOf_widget_0(propertyName);
	}

	private void HandleWidgetPropertyChangeOf_widget_0(string propertyName)
	{
		if (propertyName == "KeyID")
		{
			_datasource_Root_Key.KeyID = _widget_0.KeyID;
		}
		else if (propertyName == "IsVisible")
		{
			_datasource_Root_Key.IsVisible = ((Widget)_widget_0).IsVisible;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root(string propertyName)
	{
		switch (propertyName)
		{
		case "Key":
			RefreshDataSource_datasource_Root_Key(_datasource_Root.Key);
			break;
		case "InputType":
			_widget.InputType = _datasource_Root.InputType;
			break;
		case "ForcedKeyId":
			_widget_1.KeyId = _datasource_Root.ForcedKeyId;
			break;
		case "MovementType":
			_widget_1.MovementType = _datasource_Root.MovementType;
			_widget_2.MovementType = _datasource_Root.MovementType;
			break;
		case "ForcedKeyName":
			_widget_2_1_0.Text = _datasource_Root.ForcedKeyName;
			break;
		}
	}

	private void ViewModelPropertyChangedListenerOf_datasource_Root_Key(object sender, PropertyChangedEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(e.PropertyName);
	}

	private void ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithBoolValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithBoolValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithFloatValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithFloatValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithUIntValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithUIntValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithColorValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithColorValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithDoubleValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithDoubleValueEventArgs)(ref e)).PropertyName);
	}

	private void ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Key(object sender, PropertyChangedWithVec2ValueEventArgs e)
	{
		HandleViewModelPropertyChangeOf_datasource_Root_Key(((PropertyChangedWithVec2ValueEventArgs)(ref e)).PropertyName);
	}

	private void HandleViewModelPropertyChangeOf_datasource_Root_Key(string propertyName)
	{
		if (propertyName == "KeyID")
		{
			_widget_0.KeyID = _datasource_Root_Key.KeyID;
		}
		else if (propertyName == "IsVisible")
		{
			((Widget)_widget_0).IsVisible = _datasource_Root_Key.IsVisible;
		}
	}

	private void RefreshDataSource_datasource_Root(TrainingObjectiveKeyVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_0603: Unknown result type (might be due to invalid IL or missing references)
		//IL_060d: Expected O, but got Unknown
		//IL_061a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0624: Expected O, but got Unknown
		//IL_0631: Unknown result type (might be due to invalid IL or missing references)
		//IL_063b: Expected O, but got Unknown
		//IL_0648: Unknown result type (might be due to invalid IL or missing references)
		//IL_0652: Expected O, but got Unknown
		//IL_065f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0669: Expected O, but got Unknown
		//IL_0676: Unknown result type (might be due to invalid IL or missing references)
		//IL_0680: Expected O, but got Unknown
		//IL_068d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0697: Expected O, but got Unknown
		//IL_06a4: Unknown result type (might be due to invalid IL or missing references)
		//IL_06ae: Expected O, but got Unknown
		//IL_0445: Unknown result type (might be due to invalid IL or missing references)
		//IL_044f: Expected O, but got Unknown
		//IL_045c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0466: Expected O, but got Unknown
		//IL_0473: Unknown result type (might be due to invalid IL or missing references)
		//IL_047d: Expected O, but got Unknown
		//IL_048a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0494: Expected O, but got Unknown
		//IL_04a1: Unknown result type (might be due to invalid IL or missing references)
		//IL_04ab: Expected O, but got Unknown
		//IL_04b8: Unknown result type (might be due to invalid IL or missing references)
		//IL_04c2: Expected O, but got Unknown
		//IL_04cf: Unknown result type (might be due to invalid IL or missing references)
		//IL_04d9: Expected O, but got Unknown
		//IL_04e6: Unknown result type (might be due to invalid IL or missing references)
		//IL_04f0: Expected O, but got Unknown
		//IL_0a98: Unknown result type (might be due to invalid IL or missing references)
		//IL_0aa2: Expected O, but got Unknown
		//IL_0aaf: Unknown result type (might be due to invalid IL or missing references)
		//IL_0ab9: Expected O, but got Unknown
		//IL_0ac6: Unknown result type (might be due to invalid IL or missing references)
		//IL_0ad0: Expected O, but got Unknown
		//IL_0add: Unknown result type (might be due to invalid IL or missing references)
		//IL_0ae7: Expected O, but got Unknown
		//IL_0af4: Unknown result type (might be due to invalid IL or missing references)
		//IL_0afe: Expected O, but got Unknown
		//IL_0b0b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0b15: Expected O, but got Unknown
		//IL_0b22: Unknown result type (might be due to invalid IL or missing references)
		//IL_0b2c: Expected O, but got Unknown
		//IL_0b39: Unknown result type (might be due to invalid IL or missing references)
		//IL_0b43: Expected O, but got Unknown
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			((PropertyOwnerObject)_widget).PropertyChanged -= PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged -= boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged -= floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged -= doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged -= intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged -= uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget_1).PropertyChanged -= PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged -= intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_2).PropertyChanged -= PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged -= intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2_1_0).PropertyChanged -= PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_2_1_0;
			if (_datasource_Root_Key != null)
			{
				((ViewModel)_datasource_Root_Key).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Key;
				((ViewModel)_datasource_Root_Key).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Key);
				((PropertyOwnerObject)_widget_0).PropertyChanged -= PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
				_datasource_Root_Key = null;
			}
			_datasource_Root = null;
		}
		_datasource_Root = newDataSource;
		if (_datasource_Root != null)
		{
			((ViewModel)_datasource_Root).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root;
			((ViewModel)_datasource_Root).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root);
			((ViewModel)_datasource_Root).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root);
			_widget.InputType = _datasource_Root.InputType;
			((PropertyOwnerObject)_widget).PropertyChanged += PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).boolPropertyChanged += boolPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).floatPropertyChanged += floatPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).doublePropertyChanged += doublePropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).intPropertyChanged += intPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).uintPropertyChanged += uintPropertyChangedListenerOf_widget;
			((PropertyOwnerObject)_widget).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget;
			_widget_1.KeyId = _datasource_Root.ForcedKeyId;
			_widget_1.MovementType = _datasource_Root.MovementType;
			((PropertyOwnerObject)_widget_1).PropertyChanged += PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).boolPropertyChanged += boolPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).floatPropertyChanged += floatPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).doublePropertyChanged += doublePropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).intPropertyChanged += intPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).uintPropertyChanged += uintPropertyChangedListenerOf_widget_1;
			((PropertyOwnerObject)_widget_1).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_1;
			_widget_2.MovementType = _datasource_Root.MovementType;
			((PropertyOwnerObject)_widget_2).PropertyChanged += PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).boolPropertyChanged += boolPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).floatPropertyChanged += floatPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).doublePropertyChanged += doublePropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).intPropertyChanged += intPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).uintPropertyChanged += uintPropertyChangedListenerOf_widget_2;
			((PropertyOwnerObject)_widget_2).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2;
			_widget_2_1_0.Text = _datasource_Root.ForcedKeyName;
			((PropertyOwnerObject)_widget_2_1_0).PropertyChanged += PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).intPropertyChanged += intPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_2_1_0;
			((PropertyOwnerObject)_widget_2_1_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_2_1_0;
			_datasource_Root_Key = _datasource_Root.Key;
			if (_datasource_Root_Key != null)
			{
				((ViewModel)_datasource_Root_Key).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Key;
				((ViewModel)_datasource_Root_Key).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Key);
				((ViewModel)_datasource_Root_Key).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Key);
				_widget_0.KeyID = _datasource_Root_Key.KeyID;
				((Widget)_widget_0).IsVisible = _datasource_Root_Key.IsVisible;
				((PropertyOwnerObject)_widget_0).PropertyChanged += PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).intPropertyChanged += intPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_0;
				((PropertyOwnerObject)_widget_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0;
			}
		}
	}

	private void RefreshDataSource_datasource_Root_Key(InputKeyItemVM newDataSource)
	{
		//IL_002f: Unknown result type (might be due to invalid IL or missing references)
		//IL_0039: Expected O, but got Unknown
		//IL_0046: Unknown result type (might be due to invalid IL or missing references)
		//IL_0050: Expected O, but got Unknown
		//IL_005d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0067: Expected O, but got Unknown
		//IL_0074: Unknown result type (might be due to invalid IL or missing references)
		//IL_007e: Expected O, but got Unknown
		//IL_008b: Unknown result type (might be due to invalid IL or missing references)
		//IL_0095: Expected O, but got Unknown
		//IL_00a2: Unknown result type (might be due to invalid IL or missing references)
		//IL_00ac: Expected O, but got Unknown
		//IL_00b9: Unknown result type (might be due to invalid IL or missing references)
		//IL_00c3: Expected O, but got Unknown
		//IL_00d0: Unknown result type (might be due to invalid IL or missing references)
		//IL_00da: Expected O, but got Unknown
		//IL_01f7: Unknown result type (might be due to invalid IL or missing references)
		//IL_0201: Expected O, but got Unknown
		//IL_020e: Unknown result type (might be due to invalid IL or missing references)
		//IL_0218: Expected O, but got Unknown
		//IL_0225: Unknown result type (might be due to invalid IL or missing references)
		//IL_022f: Expected O, but got Unknown
		//IL_023c: Unknown result type (might be due to invalid IL or missing references)
		//IL_0246: Expected O, but got Unknown
		//IL_0253: Unknown result type (might be due to invalid IL or missing references)
		//IL_025d: Expected O, but got Unknown
		//IL_026a: Unknown result type (might be due to invalid IL or missing references)
		//IL_0274: Expected O, but got Unknown
		//IL_0281: Unknown result type (might be due to invalid IL or missing references)
		//IL_028b: Expected O, but got Unknown
		//IL_0298: Unknown result type (might be due to invalid IL or missing references)
		//IL_02a2: Expected O, but got Unknown
		if (_datasource_Root_Key != null)
		{
			((ViewModel)_datasource_Root_Key).PropertyChanged -= ViewModelPropertyChangedListenerOf_datasource_Root_Key;
			((ViewModel)_datasource_Root_Key).PropertyChangedWithValue -= new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithBoolValue -= new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithIntValue -= new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithFloatValue -= new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithUIntValue -= new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithColorValue -= new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithDoubleValue -= new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithVec2Value -= new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Key);
			((PropertyOwnerObject)_widget_0).PropertyChanged -= PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged -= boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged -= floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged -= Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged -= Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged -= doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged -= intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged -= uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged -= ColorPropertyChangedListenerOf_widget_0;
			_datasource_Root_Key = null;
		}
		_datasource_Root_Key = newDataSource;
		_datasource_Root_Key = _datasource_Root.Key;
		if (_datasource_Root_Key != null)
		{
			((ViewModel)_datasource_Root_Key).PropertyChanged += ViewModelPropertyChangedListenerOf_datasource_Root_Key;
			((ViewModel)_datasource_Root_Key).PropertyChangedWithValue += new PropertyChangedWithValueEventHandler(ViewModelPropertyChangedWithValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithBoolValue += new PropertyChangedWithBoolValueEventHandler(ViewModelPropertyChangedWithBoolValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithIntValue += new PropertyChangedWithIntValueEventHandler(ViewModelPropertyChangedWithIntValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithFloatValue += new PropertyChangedWithFloatValueEventHandler(ViewModelPropertyChangedWithFloatValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithUIntValue += new PropertyChangedWithUIntValueEventHandler(ViewModelPropertyChangedWithUIntValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithColorValue += new PropertyChangedWithColorValueEventHandler(ViewModelPropertyChangedWithColorValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithDoubleValue += new PropertyChangedWithDoubleValueEventHandler(ViewModelPropertyChangedWithDoubleValueListenerOf_datasource_Root_Key);
			((ViewModel)_datasource_Root_Key).PropertyChangedWithVec2Value += new PropertyChangedWithVec2ValueEventHandler(ViewModelPropertyChangedWithVec2ValueListenerOf_datasource_Root_Key);
			_widget_0.KeyID = _datasource_Root_Key.KeyID;
			((Widget)_widget_0).IsVisible = _datasource_Root_Key.IsVisible;
			((PropertyOwnerObject)_widget_0).PropertyChanged += PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).boolPropertyChanged += boolPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).floatPropertyChanged += floatPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vec2PropertyChanged += Vec2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).Vector2PropertyChanged += Vector2PropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).doublePropertyChanged += doublePropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).intPropertyChanged += intPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).uintPropertyChanged += uintPropertyChangedListenerOf_widget_0;
			((PropertyOwnerObject)_widget_0).ColorPropertyChanged += ColorPropertyChangedListenerOf_widget_0;
		}
	}
}
