using System.Collections.Generic;
using System.Linq;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.Localization;
using TaleWorlds.SaveSystem;

namespace TaleWorlds.CampaignSystem.Map;

public class MapMarkerManager
{
	[SaveableField(1)]
	private List<MapMarker> _mapMarkers = new List<MapMarker>();

	public MBReadOnlyList<MapMarker> MapMarkers => _mapMarkers.ToMBList();

	internal static void AutoGeneratedStaticCollectObjectsMapMarkerManager(object o, List<object> collectedObjects)
	{
		((MapMarkerManager)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		collectedObjects.Add(_mapMarkers);
	}

	internal static object AutoGeneratedGetMemberValue_mapMarkers(object o)
	{
		return ((MapMarkerManager)o)._mapMarkers;
	}

	public MapMarker CreateMapMarker(Banner banner, TextObject name, Vec3 position, bool isVisibleOnMap, string questId)
	{
		MapMarker mapMarker = new MapMarker(banner, name, position, isVisibleOnMap, questId);
		_mapMarkers.Add(mapMarker);
		Campaign.Current.VisualTrackerManager.RegisterObject(mapMarker);
		CampaignEventDispatcher.Instance.OnMapMarkerCreated(mapMarker);
		return mapMarker;
	}

	public void RemoveMapMarker(MapMarker mapMarker)
	{
		_mapMarkers.Remove(mapMarker);
		Campaign.Current.VisualTrackerManager.RemoveTrackedObject(mapMarker);
		CampaignEventDispatcher.Instance.OnMapMarkerRemoved(mapMarker);
	}

	public void RemoveAllMapMarkersByQuestId(string questId)
	{
		foreach (MapMarker item in GetMapMarkersByQuestId(questId).ToList())
		{
			RemoveMapMarker(item);
		}
	}

	public IEnumerable<MapMarker> GetMapMarkersByQuestId(string questId)
	{
		return _mapMarkers.Where((MapMarker x) => x.QuestId == questId);
	}
}
