using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Core;
using TaleWorlds.SaveSystem;

namespace StoryMode.Quests.QuestTasks;

public class PurchaseItemTutorialQuestTask : QuestTaskBase
{
	[SaveableField(1)]
	private readonly JournalLog _progressLog;

	private int _targetItemAmount;

	private ItemObject _item;

	[SaveableField(2)]
	private int _purchasedItemAmount;

	public PurchaseItemTutorialQuestTask(Action onSucceed, int targetItemAmount, ItemObject item, JournalLog progressLog = null)
		: base((DialogFlow)null, onSucceed, (Action)null, (Action)null)
	{
		_targetItemAmount = targetItemAmount;
		_item = item;
		_progressLog = progressLog;
		_purchasedItemAmount = 0;
	}

	public void InitializeTaskOnLoad(int targetItemAmount, ItemObject item)
	{
		_targetItemAmount = targetItemAmount;
		_item = item;
	}

	public override void SetReferences()
	{
		CampaignEvents.PlayerInventoryExchangeEvent.AddNonSerializedListener((object)this, (Action<List<(ItemRosterElement, int)>, List<(ItemRosterElement, int)>, bool>)PlayerInventoryExchange);
	}

	private void PlayerInventoryExchange(List<(ItemRosterElement, int)> purchasedItems, List<(ItemRosterElement, int)> soldItems, bool isTrading)
	{
		//IL_0020: Unknown result type (might be due to invalid IL or missing references)
		//IL_0025: Unknown result type (might be due to invalid IL or missing references)
		//IL_0028: Unknown result type (might be due to invalid IL or missing references)
		//IL_002d: Unknown result type (might be due to invalid IL or missing references)
		//IL_0045: Unknown result type (might be due to invalid IL or missing references)
		//IL_004a: Unknown result type (might be due to invalid IL or missing references)
		if (!((QuestTaskBase)this).IsActive)
		{
			return;
		}
		foreach (var purchasedItem in purchasedItems)
		{
			ItemRosterElement item = purchasedItem.Item1;
			EquipmentElement equipmentElement = ((ItemRosterElement)(ref item)).EquipmentElement;
			if (((EquipmentElement)(ref equipmentElement)).Item != _item)
			{
				continue;
			}
			int purchasedItemAmount = _purchasedItemAmount;
			item = purchasedItem.Item1;
			_purchasedItemAmount = purchasedItemAmount + ((ItemRosterElement)(ref item)).Amount;
			if (_purchasedItemAmount >= _targetItemAmount)
			{
				JournalLog progressLog = _progressLog;
				if (progressLog != null)
				{
					progressLog.UpdateCurrentProgress(_targetItemAmount);
				}
				((QuestTaskBase)this).Finish((FinishStates)0);
				break;
			}
			JournalLog progressLog2 = _progressLog;
			if (progressLog2 != null)
			{
				progressLog2.UpdateCurrentProgress(_purchasedItemAmount);
			}
		}
	}

	internal static void AutoGeneratedStaticCollectObjectsPurchaseItemTutorialQuestTask(object o, List<object> collectedObjects)
	{
		((QuestTaskBase)(PurchaseItemTutorialQuestTask)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		((QuestTaskBase)this).AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(_progressLog);
	}

	internal static object AutoGeneratedGetMemberValue_progressLog(object o)
	{
		return ((PurchaseItemTutorialQuestTask)o)._progressLog;
	}

	internal static object AutoGeneratedGetMemberValue_purchasedItemAmount(object o)
	{
		return ((PurchaseItemTutorialQuestTask)o)._purchasedItemAmount;
	}
}
