using System;
using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.SaveSystem;

namespace StoryMode.Quests.QuestTasks;

public class RecruitTroopTutorialQuestTask : QuestTaskBase
{
	private int _targetRecruitAmount;

	private Func<CharacterObject, bool> _recruitTypeConditions;

	private Settlement _recruitSettlement;

	[SaveableField(1)]
	private readonly JournalLog _progressLog;

	[SaveableField(2)]
	private int _recruitedTroopAmount;

	public RecruitTroopTutorialQuestTask(Action onSucceed, int targetRecruitAmount, Func<CharacterObject, bool> recruitTypeConditions, Settlement recruitSettlement = null, JournalLog progressLog = null)
		: base((DialogFlow)null, onSucceed, (Action)null, (Action)null)
	{
		_targetRecruitAmount = targetRecruitAmount;
		_recruitTypeConditions = recruitTypeConditions;
		_recruitSettlement = recruitSettlement;
		_progressLog = progressLog;
		_recruitedTroopAmount = 0;
	}

	public void InitializeTaskOnLoad(int targetRecruitAmount, Func<CharacterObject, bool> recruitTypeConditions, Settlement recruitSettlement = null)
	{
		_targetRecruitAmount = targetRecruitAmount;
		_recruitTypeConditions = recruitTypeConditions;
		_recruitSettlement = recruitSettlement;
	}

	public override void SetReferences()
	{
		CampaignEvents.OnUnitRecruitedEvent.AddNonSerializedListener((object)this, (Action<CharacterObject, int>)OnUnitRecruited);
	}

	private void OnUnitRecruited(CharacterObject character, int amount)
	{
		if (!((QuestTaskBase)this).IsActive || (_recruitSettlement != null && Settlement.CurrentSettlement != _recruitSettlement) || !_recruitTypeConditions(character))
		{
			return;
		}
		_recruitedTroopAmount += amount;
		if (_recruitedTroopAmount >= _targetRecruitAmount)
		{
			JournalLog progressLog = _progressLog;
			if (progressLog != null)
			{
				progressLog.UpdateCurrentProgress(_targetRecruitAmount);
			}
			((QuestTaskBase)this).Finish((FinishStates)0);
		}
		else
		{
			JournalLog progressLog2 = _progressLog;
			if (progressLog2 != null)
			{
				progressLog2.UpdateCurrentProgress(_recruitedTroopAmount);
			}
		}
	}

	internal static void AutoGeneratedStaticCollectObjectsRecruitTroopTutorialQuestTask(object o, List<object> collectedObjects)
	{
		((QuestTaskBase)(RecruitTroopTutorialQuestTask)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		((QuestTaskBase)this).AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(_progressLog);
	}

	internal static object AutoGeneratedGetMemberValue_progressLog(object o)
	{
		return ((RecruitTroopTutorialQuestTask)o)._progressLog;
	}

	internal static object AutoGeneratedGetMemberValue_recruitedTroopAmount(object o)
	{
		return ((RecruitTroopTutorialQuestTask)o)._recruitedTroopAmount;
	}
}
