using System;
using System.Collections.Generic;
using StoryMode.Quests.QuestTasks;
using StoryMode.StoryModePhases;
using TaleWorlds.CampaignSystem;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace StoryMode.Quests.TutorialPhase;

public class PurchaseGrainTutorialQuest : StoryModeQuestBase
{
	public const int BuyGrainAmount = 2;

	[SaveableField(1)]
	private readonly PurchaseItemTutorialQuestTask _purchaseItemTutorialQuestTask;

	private TextObject _buyItemTaskStartLog
	{
		get
		{
			//IL_0006: Unknown result type (might be due to invalid IL or missing references)
			//IL_000b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0022: Expected O, but got Unknown
			TextObject val = new TextObject("{=D9RoNGJg}Buy 2 {GRAIN}{.s}. Click \"Buy Products\" option on village menu to buy products.", (Dictionary<string, object>)null);
			val.SetTextVariable("GRAIN", DefaultItems.Grain.Name);
			return val;
		}
	}

	public override TextObject Title
	{
		get
		{
			//IL_0006: Unknown result type (might be due to invalid IL or missing references)
			//IL_000b: Unknown result type (might be due to invalid IL or missing references)
			//IL_0022: Expected O, but got Unknown
			TextObject val = new TextObject("{=JhEzD45J}Purchase {GRAIN}", (Dictionary<string, object>)null);
			val.SetTextVariable("GRAIN", DefaultItems.Grain.Name);
			return val;
		}
	}

	public PurchaseGrainTutorialQuest(Hero questGiver)
		: base("purchase_grain_tutorial_quest", questGiver, CampaignTime.Never)
	{
		//IL_0007: Unknown result type (might be due to invalid IL or missing references)
		//IL_0027: Unknown result type (might be due to invalid IL or missing references)
		//IL_002d: Expected O, but got Unknown
		StoryMode.StoryModePhases.TutorialPhase.Instance.InitializeTutorialVillageItemRoster();
		((QuestBase)this).SetDialogs();
		TextObject val = new TextObject("{=TLRyyRaW}Purchased {GRAIN} Amount", (Dictionary<string, object>)null);
		val.SetTextVariable("GRAIN", DefaultItems.Grain.Name);
		_purchaseItemTutorialQuestTask = new PurchaseItemTutorialQuestTask(PurchaseItemTaskOnSuccess, 2, DefaultItems.Grain, ((QuestBase)this).AddDiscreteLog(_buyItemTaskStartLog, val, 0, 2, (TextObject)null, false));
		((QuestBase)this).AddTask((QuestTaskBase)(object)_purchaseItemTutorialQuestTask);
	}

	protected override void SetDialogs()
	{
	}

	protected override void InitializeQuestOnGameLoad()
	{
		((QuestBase)this).SetDialogs();
		((QuestTaskBase)_purchaseItemTutorialQuestTask).AddTaskBehaviorsOnGameLoad((Action)PurchaseItemTaskOnSuccess, (Action)null, (Action)null);
		_purchaseItemTutorialQuestTask.InitializeTaskOnLoad(2, DefaultItems.Grain);
	}

	protected override void HourlyTick()
	{
	}

	private void PurchaseItemTaskOnSuccess()
	{
		((QuestBase)this).CompleteQuestWithSuccess();
	}

	internal static void AutoGeneratedStaticCollectObjectsPurchaseGrainTutorialQuest(object o, List<object> collectedObjects)
	{
		((MBObjectBase)(PurchaseGrainTutorialQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		((QuestBase)this).AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(_purchaseItemTutorialQuestTask);
	}

	internal static object AutoGeneratedGetMemberValue_purchaseItemTutorialQuestTask(object o)
	{
		return ((PurchaseGrainTutorialQuest)o)._purchaseItemTutorialQuestTask;
	}
}
