using System;
using System.Collections.Generic;
using StoryMode.Quests.QuestTasks;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Localization;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace StoryMode.Quests.TutorialPhase;

public class RecruitTroopsTutorialQuest : StoryModeQuestBase
{
	public const int RecruitTroopAmount = 4;

	[SaveableField(1)]
	private readonly RecruitTroopTutorialQuestTask _recruitTroopTutorialQuestTask;

	private TextObject _recruitTroopTaskStartLog => new TextObject("{=vCBuF6dq}Recruit 4 recruits. Click \"Recruit Troops\" option on village menu to recruit troops.", (Dictionary<string, object>)null);

	public override TextObject Title => new TextObject("{=y3fn2vWY}Recruit Troops", (Dictionary<string, object>)null);

	public RecruitTroopsTutorialQuest(Hero questGiver)
		: base("recruit_troops_tutorial_quest", questGiver, CampaignTime.Never)
	{
		//IL_0007: Unknown result type (might be due to invalid IL or missing references)
		//IL_0043: Unknown result type (might be due to invalid IL or missing references)
		//IL_0051: Expected O, but got Unknown
		((QuestBase)this).SetDialogs();
		_recruitTroopTutorialQuestTask = new RecruitTroopTutorialQuestTask(RecruitTaskOnSuccess, 4, DoesRecruitedTroopSatifyRecruitTroopTask, Settlement.CurrentSettlement, ((QuestBase)this).AddDiscreteLog(_recruitTroopTaskStartLog, new TextObject("{=y3fn2vWY}Recruit Troops", (Dictionary<string, object>)null), 0, 4, (TextObject)null, false));
		((QuestBase)this).AddTask((QuestTaskBase)(object)_recruitTroopTutorialQuestTask);
	}

	protected override void SetDialogs()
	{
	}

	protected override void InitializeQuestOnGameLoad()
	{
		((QuestBase)this).SetDialogs();
		((QuestTaskBase)_recruitTroopTutorialQuestTask).AddTaskBehaviorsOnGameLoad((Action)RecruitTaskOnSuccess, (Action)null, (Action)null);
		_recruitTroopTutorialQuestTask.InitializeTaskOnLoad(4, DoesRecruitedTroopSatifyRecruitTroopTask, Settlement.Find("village_ES3_2"));
	}

	protected override void HourlyTick()
	{
	}

	private bool DoesRecruitedTroopSatifyRecruitTroopTask(CharacterObject troop)
	{
		return true;
	}

	private void RecruitTaskOnSuccess()
	{
		((QuestBase)this).CompleteQuestWithSuccess();
	}

	internal static void AutoGeneratedStaticCollectObjectsRecruitTroopsTutorialQuest(object o, List<object> collectedObjects)
	{
		((MBObjectBase)(RecruitTroopsTutorialQuest)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		((QuestBase)this).AutoGeneratedInstanceCollectObjects(collectedObjects);
		collectedObjects.Add(_recruitTroopTutorialQuestTask);
	}

	internal static object AutoGeneratedGetMemberValue_recruitTroopTutorialQuestTask(object o)
	{
		return ((RecruitTroopsTutorialQuest)o)._recruitTroopTutorialQuestTask;
	}
}
