using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Party;

namespace TaleWorlds.CampaignSystem.MapEvents;

public abstract class MapEventComponent
{
	private bool _isFinished;

	public MapEvent MapEvent { get; private set; }

	public abstract MapEvent.PowerCalculationContext SimulationContext { get; }

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
	}

	protected MapEventComponent(MapEvent mapEvent)
	{
		MapEvent = mapEvent;
	}

	internal void AfterLoad(MapEvent mapEvent)
	{
		MapEvent = mapEvent;
		OnAfterLoad();
	}

	internal void InitializeComponent()
	{
		OnInitialize();
	}

	internal void BeforeFinalizeComponent()
	{
		OnBeforeFinalize();
	}

	internal void FinalizeComponent()
	{
		if (!_isFinished)
		{
			FinishComponent();
		}
		OnFinalize();
	}

	internal void FinishComponent()
	{
		_isFinished = true;
		OnFinish();
	}

	protected virtual void OnInitialize()
	{
	}

	protected virtual void OnBeforeFinalize()
	{
	}

	protected virtual void OnFinalize()
	{
	}

	internal virtual void OnPartyAdded(PartyBase party)
	{
	}

	internal virtual void OnFinish()
	{
	}

	internal virtual void Update(ref bool finish)
	{
	}

	internal virtual void OnAfterLoad()
	{
	}
}
