using System.Collections.Generic;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.Core;

namespace TaleWorlds.CampaignSystem.MapEvents;

public class SiegeAmbushEventComponent : MapEventComponent
{
	public override MapEvent.PowerCalculationContext SimulationContext
	{
		get
		{
			CampaignVec2 position = base.MapEvent.GetLeaderParty(BattleSideEnum.Attacker).SiegeEvent.BesiegerCamp.LeaderParty.Position;
			return Campaign.Current.Models.MilitaryPowerModel.GetContextForPosition(position);
		}
	}

	internal static void AutoGeneratedStaticCollectObjectsSiegeAmbushEventComponent(object o, List<object> collectedObjects)
	{
		((SiegeAmbushEventComponent)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected override void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		base.AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	public SiegeAmbushEventComponent(MapEvent mapEvent)
		: base(mapEvent)
	{
	}

	public static SiegeAmbushEventComponent CreateSiegeAmbushEvent(PartyBase attackerParty, PartyBase defenderParty)
	{
		MapEvent mapEvent = new MapEvent();
		SiegeAmbushEventComponent siegeAmbushEventComponent = new SiegeAmbushEventComponent(mapEvent);
		mapEvent.Initialize(attackerParty, defenderParty, siegeAmbushEventComponent);
		Campaign.Current.MapEventManager.OnMapEventCreated(mapEvent);
		return siegeAmbushEventComponent;
	}

	protected override void OnFinalize()
	{
		base.MapEvent.ApplyRenownAndInfluenceChanges();
	}
}
