using System.Collections.Generic;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Actions;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.ObjectSystem;
using TaleWorlds.SaveSystem;

namespace StoryMode.StoryModePhases;

public class TutorialPhase
{
	private const int GrainAmount = 3;

	private const int RecruitTroopAmount = 6;

	public const int RestrictedModePriority = 1000000;

	public const string QuestVillageStringId = "village_ES3_2";

	public const string TrainingFieldStringId = "tutorial_training_field";

	public const string RadagosRaidersStringId = "storymode_quest_raider";

	public const string TutorialVolunteerStringId = "tutorial_placeholder_volunteer";

	public const string TutorialFemaleRefugeeStringId = "storymode_quest_refugee_female";

	public const string TutorialMaleRefugeeStringId = "storymode_quest_refugee_male";

	public const string TutorialHeadmanStringId = "storymode_tutorial_headman";

	[SaveableField(1)]
	private readonly ItemRoster _tutorialPhaseShoppingRoster;

	public static TutorialPhase Instance => StoryModeManager.Current?.MainStoryLine?.TutorialPhase;

	[SaveableProperty(2)]
	public Settlement TutorialFocusSettlement { get; private set; }

	[SaveableProperty(3)]
	public MobileParty TutorialFocusMobileParty { get; private set; }

	public bool IsCompleted => TutorialQuestPhase == TutorialQuestPhase.Finalized;

	[SaveableProperty(5)]
	public bool TalkedWithBrotherForTheFirstTime { get; private set; }

	[SaveableProperty(6)]
	public bool LockTutorialVillageEnter { get; private set; }

	[SaveableProperty(7)]
	public TutorialQuestPhase TutorialQuestPhase { get; private set; }

	[SaveableProperty(8)]
	public bool IsSkipped { get; private set; }

	[CachedData]
	public Hero TutorialVillageHeadman { get; set; }

	internal static void AutoGeneratedStaticCollectObjectsTutorialPhase(object o, List<object> collectedObjects)
	{
		((TutorialPhase)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
	}

	protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects)
	{
		collectedObjects.Add(_tutorialPhaseShoppingRoster);
		collectedObjects.Add(TutorialFocusSettlement);
		collectedObjects.Add(TutorialFocusMobileParty);
	}

	internal static object AutoGeneratedGetMemberValueTutorialFocusSettlement(object o)
	{
		return ((TutorialPhase)o).TutorialFocusSettlement;
	}

	internal static object AutoGeneratedGetMemberValueTutorialFocusMobileParty(object o)
	{
		return ((TutorialPhase)o).TutorialFocusMobileParty;
	}

	internal static object AutoGeneratedGetMemberValueTalkedWithBrotherForTheFirstTime(object o)
	{
		return ((TutorialPhase)o).TalkedWithBrotherForTheFirstTime;
	}

	internal static object AutoGeneratedGetMemberValueLockTutorialVillageEnter(object o)
	{
		return ((TutorialPhase)o).LockTutorialVillageEnter;
	}

	internal static object AutoGeneratedGetMemberValueTutorialQuestPhase(object o)
	{
		return ((TutorialPhase)o).TutorialQuestPhase;
	}

	internal static object AutoGeneratedGetMemberValueIsSkipped(object o)
	{
		return ((TutorialPhase)o).IsSkipped;
	}

	internal static object AutoGeneratedGetMemberValue_tutorialPhaseShoppingRoster(object o)
	{
		return ((TutorialPhase)o)._tutorialPhaseShoppingRoster;
	}

	public TutorialPhase()
	{
		//IL_0007: Unknown result type (might be due to invalid IL or missing references)
		//IL_0011: Expected O, but got Unknown
		_tutorialPhaseShoppingRoster = new ItemRoster();
		TutorialFocusSettlement = null;
		TutorialFocusMobileParty = null;
		TalkedWithBrotherForTheFirstTime = false;
		LockTutorialVillageEnter = false;
		TutorialQuestPhase = TutorialQuestPhase.None;
		IsSkipped = false;
	}

	public void PlayerTalkedWithBrotherForTheFirstTime()
	{
		TalkedWithBrotherForTheFirstTime = true;
	}

	public void SetLockTutorialVillageEnter(bool value)
	{
		LockTutorialVillageEnter = value;
	}

	public void CompleteTutorial(bool isSkipped)
	{
		TutorialQuestPhase = TutorialQuestPhase.Finalized;
		RemoveTutorialFocusSettlement();
		RemoveTutorialFocusMobileParty();
		IsSkipped = isSkipped;
	}

	public void SetTutorialFocusSettlement(Settlement settlement)
	{
		TutorialFocusSettlement = settlement;
	}

	public void RemoveTutorialFocusSettlement()
	{
		TutorialFocusSettlement = null;
	}

	public void RemoveTutorialFocusMobileParty()
	{
		TutorialFocusMobileParty = null;
	}

	public void PrepareRecruitOptionForTutorial()
	{
		//IL_007a: Unknown result type (might be due to invalid IL or missing references)
		//IL_007f: Unknown result type (might be due to invalid IL or missing references)
		bool flag = 6 - (MobileParty.MainParty.MemberRoster.TotalManCount - 2) > 0;
		Hero val = ((List<Hero>)(object)Settlement.CurrentSettlement.Notables)[0];
		CharacterObject val2 = MBObjectManager.Instance.GetObject<CharacterObject>("tutorial_placeholder_volunteer");
		for (int i = 0; i < val.VolunteerTypes.Length; i++)
		{
			if (flag || val.VolunteerTypes[i] != null)
			{
				val.VolunteerTypes[i] = val2;
			}
		}
		if (flag)
		{
			ExplainedNumber troopRecruitmentCost = Campaign.Current.Models.PartyWageModel.GetTroopRecruitmentCost(val2, Hero.MainHero, false);
			int roundedResultNumber = ((ExplainedNumber)(ref troopRecruitmentCost)).RoundedResultNumber;
			int num = 6 * roundedResultNumber;
			if (Hero.MainHero.Gold < num)
			{
				GiveGoldAction.ApplyBetweenCharacters((Hero)null, Hero.MainHero, num, false);
			}
		}
	}

	public ItemRoster GetAndPrepareBuyProductsOptionForTutorial(Village village)
	{
		if (PartyBase.MainParty.ItemRoster.TotalFood <= 3)
		{
			_tutorialPhaseShoppingRoster.AddToCounts(DefaultItems.Grain, 3);
			int num = ((SettlementComponent)village).GetItemPrice(DefaultItems.Grain, (MobileParty)null, false) * 3;
			if (Hero.MainHero.Gold < num)
			{
				GiveGoldAction.ApplyBetweenCharacters((Hero)null, Hero.MainHero, num, false);
			}
		}
		return _tutorialPhaseShoppingRoster;
	}

	public void SetTutorialQuestPhase(TutorialQuestPhase tutorialQuestPhase)
	{
		TutorialQuestPhase = tutorialQuestPhase;
	}

	public void InitializeTutorialVillageItemRoster()
	{
		Settlement val = MBObjectManager.Instance.GetObject<Settlement>("village_ES3_2");
		for (int i = 0; i < val.ItemRoster.Count; i++)
		{
			ItemObject itemAtIndex = val.ItemRoster.GetItemAtIndex(i);
			if (itemAtIndex != null && !itemAtIndex.IsFood)
			{
				_tutorialPhaseShoppingRoster.AddToCounts(itemAtIndex, MBRandom.RandomInt(1, 4));
			}
		}
	}
}
